# Generated by Django 6.0.4 on 2026-07-15 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('fecha', models.DateField()),
                ('tipo_control', models.CharField(max_length=200)),
                ('resultados', models.TextField(blank=True, default='')),
                ('recomendaciones', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, upload_to='controles_salud/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_salud', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_salud', to='workers.worker')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Control de Salud',
                'verbose_name_plural': 'Controles de Salud',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ReconocimientoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inicial', 'Reconocimiento Inicial'), ('periodico', 'Reconocimiento Periódico'), ('especial', 'Reconocimiento Especial'), ('aptitud', 'Control de Aptitud')], max_length=20)),
                ('fecha', models.DateField()),
                ('proximo_reconocimiento', models.DateField(blank=True, null=True)),
                ('apto', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('medico', models.CharField(blank=True, default='', max_length=200)),
                ('file', models.FileField(blank=True, upload_to='reconocimientos_medicos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos_medicos', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos_medicos', to='workers.worker')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Reconocimiento Médico',
                'verbose_name_plural': 'Reconocimientos Médicos',
                'ordering': ['-fecha'],
            },
        ),
    ]
