# Generated by Django 6.0.4 on 2026-07-15 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='prioridad')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='fecha límite')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completada el')),
                ('object_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='id del objeto')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada el')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='asignada a')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='companies.company', verbose_name='empresa')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='tipo de objeto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('alert_type', models.CharField(choices=[('document_expiry', 'Caducidad documental'), ('document_review', 'Revisión documental'), ('training_expiry', 'Caducidad de formación'), ('health_surveillance', 'Vigilancia de la salud'), ('generic', 'Genérica')], default='generic', max_length=30, verbose_name='tipo de alerta')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Aviso'), ('danger', 'Crítica')], default='warning', max_length=20, verbose_name='criticidad')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='fecha objetivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('is_read', models.BooleanField(default=False, verbose_name='leída')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='leída el')),
                ('object_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='id del objeto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada el')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='companies.company', verbose_name='empresa')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='tipo de objeto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='tasks.task', verbose_name='tarea relacionada')),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertas',
                'ordering': ['-is_active', 'due_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['company', 'status'], name='tasks_task_company_c23f28_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['company', 'due_date'], name='tasks_task_company_912aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority', 'status'], name='tasks_task_priorit_685c61_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['company', 'is_active'], name='tasks_alert_company_ba539d_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'severity'], name='tasks_alert_alert_t_bdd32f_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['due_date'], name='tasks_alert_due_dat_699866_idx'),
        ),
    ]
