# Generated by Django 6.0.5 on 2026-05-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='object_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='id del objeto'),
        ),
        migrations.AlterField(
            model_name='task',
            name='object_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='id del objeto'),
        ),
    ]
