# Generated by Django 6.0.5 on 2026-07-14 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_migrate_platform_admin_role'),
        ('corrective_actions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='título de la auditoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción / alcance')),
                ('fecha_planificada', models.DateField(verbose_name='fecha planificada')),
                ('fecha_realizacion', models.DateField(blank=True, null=True, verbose_name='fecha de realización')),
                ('auditados', models.TextField(blank=True, default='', verbose_name='personas auditadas / áreas')),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_curso', 'En curso'), ('completada', 'Completada'), ('informe_pendiente', 'Informe pendiente'), ('cerrada', 'Cerrada')], default='planificada', max_length=25, verbose_name='estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones generales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_internas', to='companies.company', verbose_name='empresa')),
                ('equipo_auditor', models.ManyToManyField(blank=True, related_name='auditorias_equipo', to=settings.AUTH_USER_MODEL, verbose_name='equipo auditor')),
                ('lider_auditoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lider_auditorias', to=settings.AUTH_USER_MODEL, verbose_name='líder de auditoría')),
            ],
            options={
                'verbose_name': 'auditoría interna',
                'verbose_name_plural': 'auditorías internas',
                'ordering': ['-fecha_planificada', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InformeAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen_ejecutivo', models.TextField(verbose_name='resumen ejecutivo')),
                ('hallazgos_resumen', models.TextField(verbose_name='resumen de hallazgos')),
                ('puntos_fuertes', models.TextField(blank=True, default='', verbose_name='puntos fuertes')),
                ('oportunidades_mejora', models.TextField(blank=True, default='', verbose_name='oportunidades de mejora')),
                ('recomendaciones', models.TextField(blank=True, default='', verbose_name='recomendaciones')),
                ('fecha_informe', models.DateField(verbose_name='fecha del informe')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='fecha de aprobación')),
                ('archivo_pdf', models.FileField(blank=True, upload_to='auditorias/informes/', verbose_name='informe PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='aprobado por')),
                ('auditoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe', to='audits.auditoriainterna', verbose_name='auditoría')),
                ('elaborado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes_elaborados', to=settings.AUTH_USER_MODEL, verbose_name='elaborado por')),
            ],
            options={
                'verbose_name': 'informe de auditoría',
                'verbose_name_plural': 'informes de auditoría',
                'ordering': ['-fecha_informe', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='año del programa')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='versión')),
                ('alcance', models.TextField(blank=True, default='', help_text='Cláusulas ISO 45001 incluidas en el programa anual', verbose_name='alcance')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='fecha de aprobación')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('en_ejecucion', 'En ejecución'), ('completado', 'Completado')], default='borrador', max_length=20, verbose_name='estado')),
                ('notas', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='aprobado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_auditoria', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'programa de auditoría',
                'verbose_name_plural': 'programas de auditoría',
                'ordering': ['-anio', '-created_at'],
                'unique_together': {('empresa', 'anio')},
            },
        ),
        migrations.AddField(
            model_name='auditoriainterna',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='audits.programaauditoria', verbose_name='programa de auditoría'),
        ),
        migrations.CreateModel(
            name='ChecklistAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clausula_iso', models.CharField(help_text='ej: 4.1, 5.2, 8.1.2, 9.2.1', max_length=20, verbose_name='cláusula ISO 45001')),
                ('seccion', models.CharField(blank=True, default='', help_text='Nombre de la sección de la cláusula', max_length=200, verbose_name='sección')),
                ('requisito', models.TextField(verbose_name='requisito / pregunta de auditoría')),
                ('evidencia_requerida', models.TextField(blank=True, default='', help_text='Qué evidencia debe presentarse', verbose_name='evidencia requerida')),
                ('conformidad', models.CharField(blank=True, choices=[('conforme', 'Conforme'), ('no_conforme', 'No conforme'), ('observacion', 'Observación'), ('no_aplica', 'No aplica')], default='', max_length=20, verbose_name='conformidad')),
                ('hallazgo', models.TextField(blank=True, default='', verbose_name='hallazgo / descripción del resultado')),
                ('evidencia_encontrada', models.TextField(blank=True, default='', verbose_name='evidencia encontrada')),
                ('plazo_cierre', models.DateField(blank=True, null=True, verbose_name='plazo de cierre')),
                ('cerrado', models.BooleanField(default=False, verbose_name='cerrado')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='fecha de cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('accion_correctiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_auditoria', to='corrective_actions.noconformidad', verbose_name='no conformidad generada')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='audits.auditoriainterna', verbose_name='auditoría')),
                ('responsable_seguimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_seguimiento', to=settings.AUTH_USER_MODEL, verbose_name='responsable de seguimiento')),
            ],
            options={
                'verbose_name': 'item de checklist de auditoría',
                'verbose_name_plural': 'items de checklist de auditoría',
                'ordering': ['clausula_iso', 'seccion'],
                'indexes': [models.Index(fields=['auditoria', 'conformidad'], name='audits_chec_auditor_a494a2_idx'), models.Index(fields=['clausula_iso'], name='audits_chec_clausul_3e5581_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='auditoriainterna',
            index=models.Index(fields=['empresa', 'estado'], name='audits_audi_empresa_c5eddf_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriainterna',
            index=models.Index(fields=['empresa', 'fecha_planificada'], name='audits_audi_empresa_9315e1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriainterna',
            index=models.Index(fields=['programa'], name='audits_audi_program_7e856a_idx'),
        ),
    ]
