# Generated by Django 6.0.4 on 2026-07-15 17:46

import apps.companies.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255, verbose_name='razón social')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='nombre comercial')),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='CIF/NIF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('website', models.URLField(blank=True, verbose_name='sitio web')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='código postal')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='provincia')),
                ('autonomous_community', models.CharField(blank=True, max_length=100, verbose_name='comunidad autónoma')),
                ('country', models.CharField(default='España', max_length=100, verbose_name='país')),
                ('activity', models.CharField(blank=True, max_length=255, verbose_name='actividad')),
                ('cnae', models.CharField(blank=True, max_length=10, verbose_name='CNAE')),
                ('workforce_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='número de trabajadores')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.companies.models.company_logo_upload_path, verbose_name='logo')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('prospect', 'Prospecto')], default='active', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('company_admin', 'Administrador empresa'), ('technician', 'Técnico PRL'), ('manager', 'Responsable'), ('reader', 'Solo lectura')], default='reader', max_length=30, verbose_name='rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_default', models.BooleanField(default=False, verbose_name='empresa por defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.company', verbose_name='empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'membresía de empresa',
                'verbose_name_plural': 'membresías de empresa',
                'ordering': ['company__legal_name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='unique_user_company_membership'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('user',), name='unique_active_default_company_per_user')],
            },
        ),
    ]
