# Generated by Django 6.0.5 on 2026-05-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255, verbose_name='razón social')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='nombre comercial')),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='CIF/NIF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('website', models.URLField(blank=True, verbose_name='sitio web')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='código postal')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='provincia')),
                ('autonomous_community', models.CharField(blank=True, max_length=100, verbose_name='comunidad autónoma')),
                ('country', models.CharField(default='España', max_length=100, verbose_name='país')),
                ('activity', models.CharField(blank=True, max_length=255, verbose_name='actividad')),
                ('cnae', models.CharField(blank=True, max_length=10, verbose_name='CNAE')),
                ('workforce_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='número de trabajadores')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('prospect', 'Prospecto')], default='active', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['legal_name'],
            },
        ),
    ]
