# Generated by Django 6.0.5 on 2026-05-11 13:51

import apps.companies.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.companies.models.company_logo_upload_path, verbose_name='logo'),
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('platform_admin', 'Administrador plataforma'), ('company_admin', 'Administrador empresa'), ('technician', 'Técnico PRL'), ('manager', 'Responsable'), ('reader', 'Solo lectura')], default='reader', max_length=30, verbose_name='rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_default', models.BooleanField(default=False, verbose_name='empresa por defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.company', verbose_name='empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'membresía de empresa',
                'verbose_name_plural': 'membresías de empresa',
                'ordering': ['company__legal_name'],
                'unique_together': {('user', 'company')},
            },
        ),
    ]
