# Generated by Django 6.0.5 on 2026-05-15 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_logo_companymembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companymembership',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='companymembership',
            name='role',
            field=models.CharField(choices=[('company_admin', 'Administrador empresa'), ('technician', 'Técnico PRL'), ('manager', 'Responsable'), ('reader', 'Solo lectura')], default='reader', max_length=30, verbose_name='rol'),
        ),
        migrations.AddConstraint(
            model_name='companymembership',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='unique_user_company_membership'),
        ),
        migrations.AddConstraint(
            model_name='companymembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('user',), name='unique_active_default_company_per_user'),
        ),
    ]
