# Generated by Django 6.0.5 on 2026-05-15 12:04

from django.db import migrations


def forwards(apps, schema_editor):
    CompanyMembership = apps.get_model('companies', 'CompanyMembership')
    CompanyMembership.objects.filter(role='platform_admin').update(role='company_admin')


def backwards(apps, schema_editor):
    CompanyMembership = apps.get_model('companies', 'CompanyMembership')
    CompanyMembership.objects.filter(role='company_admin').update(role='platform_admin')


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companymembership_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
