# Generated by Django 6.0.4 on 2026-07-15 17:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('documents', '0001_initial'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nombre')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='código')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'categoría de formación',
                'verbose_name_plural': 'categorías de formación',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='código')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('objective', models.TextField(blank=True, verbose_name='objetivo')),
                ('content', models.TextField(blank=True, verbose_name='contenido')),
                ('modality', models.CharField(choices=[('presential', 'Presencial'), ('online', 'Online'), ('mixed', 'Mixta')], default='presential', max_length=20, verbose_name='modalidad')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='duración (horas)')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='obligatoria')),
                ('requires_renewal', models.BooleanField(default=False, verbose_name='requiere renovación')),
                ('validity_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='validez')),
                ('validity_unit', models.CharField(blank=True, choices=[('days', 'Días'), ('months', 'Meses'), ('years', 'Años')], max_length=10, verbose_name='unidad de validez')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='training.trainingcategory', verbose_name='categoría')),
                ('company', models.ForeignKey(blank=True, help_text='Déjalo vacío si el curso es una plantilla general reutilizable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_courses', to='companies.company', verbose_name='empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('required_for_job_positions', models.ManyToManyField(blank=True, related_name='required_training_courses', to='workers.jobposition', verbose_name='obligatoria para puestos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'curso de formación',
                'verbose_name_plural': 'cursos de formación',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planificada'), ('in_progress', 'En curso'), ('completed', 'Completada'), ('expired', 'Caducada'), ('cancelled', 'Cancelada')], default='planned', max_length=20, verbose_name='estado')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='fecha planificada')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='fecha de realización')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='fecha de caducidad')),
                ('trainer_name', models.CharField(blank=True, max_length=150, verbose_name='formador')),
                ('training_entity', models.CharField(blank=True, max_length=150, verbose_name='entidad formadora')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='nº de certificado')),
                ('attendance_percentage', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='asistencia (%)')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='calificación')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('effectiveness_validated', models.BooleanField(default=False)),
                ('effectiveness_notes', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='companies.company', verbose_name='empresa')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='training.trainingcourse', verbose_name='curso')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_records', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('evidence_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_records', to='documents.document')),
                ('job_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_records', to='workers.jobposition', verbose_name='puesto de trabajo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_training_records', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='workers.worker', verbose_name='trabajador')),
            ],
            options={
                'verbose_name': 'registro de formación',
                'verbose_name_plural': 'registros de formación',
                'ordering': ['-planned_date', '-completed_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('scheduled', 'Planificada'), ('completed', 'Completada'), ('exempt', 'Exenta')], default='pending', max_length=20)),
                ('source', models.CharField(default='job_position', help_text='Origen de la necesidad: puesto, cambio, incidencia, auditoría, etc.', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_needs', to='companies.company')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_needs', to='training.trainingcourse')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('job_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_needs', to='workers.jobposition')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_needs', to='workers.worker')),
                ('related_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_needs', to='training.trainingrecord')),
            ],
            options={
                'verbose_name': 'Necesidad formativa',
                'verbose_name_plural': 'Necesidades formativas',
                'ordering': ['priority', 'due_date', 'worker__last_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('file', models.FileField(upload_to='training/documents/', verbose_name='archivo')),
                ('document_type', models.CharField(blank=True, max_length=100, verbose_name='tipo de documento')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='subido el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='training.trainingrecord', verbose_name='registro de formación')),
            ],
            options={
                'verbose_name': 'documento de formación',
                'verbose_name_plural': 'documentos de formación',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('alert_type', models.CharField(choices=[('expiring', 'Caducidad próxima'), ('expired', 'Caducado'), ('missing', 'Formación pendiente'), ('effectiveness', 'Eficacia pendiente')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('triggered_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_alerts', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_alerts', to='workers.worker')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='training.trainingcourse')),
                ('need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='training.trainingneed')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='training.trainingrecord')),
            ],
            options={
                'verbose_name': 'Alerta de formación',
                'verbose_name_plural': 'Alertas de formación',
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('renewal_months', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requirements', to='companies.company')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='training.trainingcourse')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requirements', to='workers.jobposition')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Requisito formativo',
                'verbose_name_plural': 'Requisitos formativos',
                'ordering': ['job_position__name', 'course__name'],
            },
        ),
        migrations.AddField(
            model_name='trainingneed',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_needs', to='training.trainingrequirement'),
        ),
        migrations.AddIndex(
            model_name='trainingcategory',
            index=models.Index(fields=['name'], name='training_tr_name_4341b9_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcategory',
            index=models.Index(fields=['code'], name='training_tr_code_e41b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcategory',
            index=models.Index(fields=['is_active'], name='training_tr_is_acti_d31e01_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['name'], name='training_tr_name_0de591_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['code'], name='training_tr_code_e8af6f_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['status'], name='training_tr_status_3539fc_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['is_mandatory'], name='training_tr_is_mand_38afca_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['requires_renewal'], name='training_tr_require_cd03bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingcourse',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_training_course_company_name'),
        ),
        migrations.AddConstraint(
            model_name='trainingcourse',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_training_course_company_code'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['company'], name='training_tr_company_eeb80b_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['worker'], name='training_tr_worker__e64f40_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['course'], name='training_tr_course__708c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['status'], name='training_tr_status_67d69a_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['planned_date'], name='training_tr_planned_25e4fb_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['completed_date'], name='training_tr_complet_fa4dca_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['expiry_date'], name='training_tr_expiry__36d538_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingrecord',
            constraint=models.UniqueConstraint(fields=('worker', 'course', 'completed_date'), name='unique_worker_course_completed_date'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingrequirement',
            unique_together={('company', 'job_position', 'course')},
        ),
    ]
