# Generated by Django 6.0.5 on 2026-05-10 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0004_alter_worker_national_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Categoría de formación',
                'verbose_name_plural': 'Categorías de formación',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('objective', models.TextField(blank=True, verbose_name='Objetivo')),
                ('content', models.TextField(blank=True, verbose_name='Contenido')),
                ('modality', models.CharField(choices=[('presential', 'Presencial'), ('online', 'Online'), ('mixed', 'Mixta')], default='presential', max_length=20, verbose_name='Modalidad')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Duración (horas)')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Obligatoria')),
                ('requires_renewal', models.BooleanField(default=False, verbose_name='Requiere renovación')),
                ('validity_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Validez')),
                ('validity_unit', models.CharField(blank=True, choices=[('days', 'Días'), ('months', 'Meses'), ('years', 'Años')], max_length=10, verbose_name='Unidad de validez')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='training.trainingcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Curso de formación',
                'verbose_name_plural': 'Cursos de formación',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planificada'), ('in_progress', 'En curso'), ('completed', 'Completada'), ('expired', 'Caducada'), ('cancelled', 'Cancelada')], default='planned', max_length=20, verbose_name='Estado')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Fecha planificada')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Fecha de realización')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de caducidad')),
                ('trainer_name', models.CharField(blank=True, max_length=150, verbose_name='Formador')),
                ('training_entity', models.CharField(blank=True, max_length=150, verbose_name='Entidad formadora')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Nº de certificado')),
                ('attendance_percentage', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Asistencia (%)')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Calificación')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='training.trainingcourse', verbose_name='Curso')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_records', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='workers.worker', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Registro de formación',
                'verbose_name_plural': 'Registros de formación',
                'ordering': ['-planned_date', '-completed_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('file', models.FileField(upload_to='training/documents/', verbose_name='Archivo')),
                ('document_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de documento')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='training.trainingrecord', verbose_name='Registro de formación')),
            ],
            options={
                'verbose_name': 'Documento de formación',
                'verbose_name_plural': 'Documentos de formación',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['name'], name='training_tr_name_0de591_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['code'], name='training_tr_code_e8af6f_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['is_active'], name='training_tr_is_acti_16b1e5_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['status'], name='training_tr_status_67d69a_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['planned_date'], name='training_tr_planned_25e4fb_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['completed_date'], name='training_tr_complet_fa4dca_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['expiry_date'], name='training_tr_expiry__36d538_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingrecord',
            constraint=models.UniqueConstraint(fields=('worker', 'course', 'completed_date'), name='unique_worker_course_completed_date'),
        ),
    ]
