# Generated by Django 6.0.5 on 2026-05-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        ('workers', '0004_alter_worker_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='required_for_job_positions',
            field=models.ManyToManyField(blank=True, related_name='required_training_courses', to='workers.jobposition', verbose_name='Obligatoria para puestos'),
        ),
    ]
