# Generated by Django 6.0.5 on 2026-05-10 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('training', '0002_trainingcourse_required_for_job_positions'),
        ('workers', '0004_alter_worker_national_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingcategory',
            options={'ordering': ['name'], 'verbose_name': 'categoría de formación', 'verbose_name_plural': 'categorías de formación'},
        ),
        migrations.AlterModelOptions(
            name='trainingcourse',
            options={'ordering': ['name'], 'verbose_name': 'curso de formación', 'verbose_name_plural': 'cursos de formación'},
        ),
        migrations.AlterModelOptions(
            name='trainingdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'documento de formación', 'verbose_name_plural': 'documentos de formación'},
        ),
        migrations.AlterModelOptions(
            name='trainingrecord',
            options={'ordering': ['-planned_date', '-completed_date', '-created_at'], 'verbose_name': 'registro de formación', 'verbose_name_plural': 'registros de formación'},
        ),
        migrations.RemoveIndex(
            model_name='trainingcourse',
            name='training_tr_is_acti_16b1e5_idx',
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Déjalo vacío si el curso es una plantilla general reutilizable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_courses', to='companies.company', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='companies.company', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_records', to='workers.jobposition', verbose_name='puesto de trabajo'),
        ),
        migrations.AlterField(
            model_name='trainingcategory',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='trainingcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='trainingcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='trainingcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activa'),
        ),
        migrations.AlterField(
            model_name='trainingcategory',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='trainingcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='training.trainingcategory', verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='content',
            field=models.TextField(blank=True, verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='duración (horas)'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='is_mandatory',
            field=models.BooleanField(default=True, verbose_name='obligatoria'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='modality',
            field=models.CharField(choices=[('presential', 'Presencial'), ('online', 'Online'), ('mixed', 'Mixta')], default='presential', max_length=20, verbose_name='modalidad'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='objective',
            field=models.TextField(blank=True, verbose_name='objetivo'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='required_for_job_positions',
            field=models.ManyToManyField(blank=True, related_name='required_training_courses', to='workers.jobposition', verbose_name='obligatoria para puestos'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='requires_renewal',
            field=models.BooleanField(default=False, verbose_name='requiere renovación'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='validity_unit',
            field=models.CharField(blank=True, choices=[('days', 'Días'), ('months', 'Meses'), ('years', 'Años')], max_length=10, verbose_name='unidad de validez'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='validity_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='validez'),
        ),
        migrations.AlterField(
            model_name='trainingdocument',
            name='document_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='tipo de documento'),
        ),
        migrations.AlterField(
            model_name='trainingdocument',
            name='file',
            field=models.FileField(upload_to='training/documents/', verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='trainingdocument',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='trainingdocument',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='trainingdocument',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='training.trainingrecord', verbose_name='registro de formación'),
        ),
        migrations.AlterField(
            model_name='trainingdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='subido el'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='attendance_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='asistencia (%)'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='nº de certificado'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de realización'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='training.trainingcourse', verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_records', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de caducidad'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha planificada'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='calificación'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='status',
            field=models.CharField(choices=[('planned', 'Planificada'), ('in_progress', 'En curso'), ('completed', 'Completada'), ('expired', 'Caducada'), ('cancelled', 'Cancelada')], default='planned', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='trainer_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='formador'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='training_entity',
            field=models.CharField(blank=True, max_length=150, verbose_name='entidad formadora'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='workers.worker', verbose_name='trabajador'),
        ),
        migrations.AddIndex(
            model_name='trainingcategory',
            index=models.Index(fields=['name'], name='training_tr_name_4341b9_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcategory',
            index=models.Index(fields=['code'], name='training_tr_code_e41b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcategory',
            index=models.Index(fields=['is_active'], name='training_tr_is_acti_d31e01_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['status'], name='training_tr_status_3539fc_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['is_mandatory'], name='training_tr_is_mand_38afca_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['requires_renewal'], name='training_tr_require_cd03bb_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['company'], name='training_tr_company_eeb80b_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['worker'], name='training_tr_worker__e64f40_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['course'], name='training_tr_course__708c3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingcourse',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_training_course_company_name'),
        ),
        migrations.AddConstraint(
            model_name='trainingcourse',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_training_course_company_code'),
        ),
        migrations.RemoveField(
            model_name='trainingcourse',
            name='is_active',
        ),
    ]
