# Generated by Django 6.0.5 on 2026-05-15 15:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_migrate_platform_admin_role'),
        ('documents', '0001_initial'),
        ('training', '0003_alter_trainingcategory_options_and_more'),
        ('workers', '0004_alter_worker_national_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='effectiveness_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='effectiveness_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='evidence_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_records', to='documents.document'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_training_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TrainingNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('scheduled', 'Planificada'), ('completed', 'Completada'), ('exempt', 'Exenta')], default='pending', max_length=20)),
                ('source', models.CharField(default='job_position', help_text='Origen de la necesidad: puesto, cambio, incidencia, auditoría, etc.', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_needs', to='companies.company')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_needs', to='training.trainingcourse')),
                ('job_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_needs', to='workers.jobposition')),
                ('related_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_needs', to='training.trainingrecord')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_needs', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Necesidad formativa',
                'verbose_name_plural': 'Necesidades formativas',
                'ordering': ['priority', 'due_date', 'worker__last_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('expiring', 'Caducidad próxima'), ('expired', 'Caducado'), ('missing', 'Formación pendiente'), ('effectiveness', 'Eficacia pendiente')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('triggered_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_alerts', to='companies.company')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='training.trainingcourse')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='training.trainingrecord')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_alerts', to='workers.worker')),
                ('need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='training.trainingneed')),
            ],
            options={
                'verbose_name': 'Alerta de formación',
                'verbose_name_plural': 'Alertas de formación',
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('renewal_months', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requirements', to='companies.company')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='training.trainingcourse')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requirements', to='workers.jobposition')),
            ],
            options={
                'verbose_name': 'Requisito formativo',
                'verbose_name_plural': 'Requisitos formativos',
                'ordering': ['job_position__name', 'course__name'],
                'unique_together': {('company', 'job_position', 'course')},
            },
        ),
        migrations.AddField(
            model_name='trainingneed',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_needs', to='training.trainingrequirement'),
        ),
    ]
