# Generated by Django 6.0.5 on 2026-07-12 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_migrate_platform_admin_role'),
        ('workcenters', '0001_initial'),
        ('workers', '0004_alter_worker_national_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='codigo')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('fuente', models.CharField(choices=[('interna', 'Interna'), ('externa', 'Externa'), ('auditoria', 'Auditoria'), ('reclamacion', 'Reclamacion'), ('inspeccion', 'Inspeccion'), ('accidente', 'Accidente')], default='interna', max_length=20, verbose_name='fuente')),
                ('gravedad', models.CharField(choices=[('menor', 'Menor'), ('moderada', 'Moderada'), ('importante', 'Importante'), ('critica', 'Critica')], default='moderada', max_length=20, verbose_name='gravedad')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_investigacion', 'En investigacion'), ('en_tratamiento', 'En tratamiento'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='abierta', max_length=20, verbose_name='estado')),
                ('fecha_deteccion', models.DateField(verbose_name='fecha de deteccion')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='ubicacion especifica')),
                ('causa_raiz', models.TextField(blank=True, verbose_name='causa raiz')),
                ('metodo_causa_raiz', models.CharField(choices=[('_5_porques', '5 Porques'), ('ishikawa', 'Ishikawa (Espina de pez)'), ('otro', 'Otro')], default='_5_porques', max_length=20, verbose_name='metodo de analisis')),
                ('evidencias', models.TextField(blank=True, verbose_name='evidencias')),
                ('archivo_evidencia', models.FileField(blank=True, upload_to='corrective_actions/evidencias/', verbose_name='archivo de evidencia')),
                ('fecha_limite_resolucion', models.DateField(verbose_name='fecha limite de resolucion')),
                ('resuelta_en', models.DateField(blank=True, null=True, verbose_name='fecha de resolucion')),
                ('verificada', models.BooleanField(default=False, verbose_name='verificada')),
                ('fecha_verificacion', models.DateField(blank=True, null=True, verbose_name='fecha de verificacion')),
                ('notas_verificacion', models.TextField(blank=True, verbose_name='notas de verificacion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_conformidades', to='workcenters.workcenter', verbose_name='centro de trabajo')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nc_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('detectado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nc_detectadas', to=settings.AUTH_USER_MODEL, verbose_name='detectado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_conformidades', to='companies.company', verbose_name='empresa')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_conformidades', to='workers.worker', verbose_name='trabajador')),
                ('verificada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nc_verificadas', to=settings.AUTH_USER_MODEL, verbose_name='verificada por')),
            ],
            options={
                'verbose_name': 'no conformidad',
                'verbose_name_plural': 'no conformidades',
                'ordering': ['-fecha_deteccion', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccionPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('fecha_limite', models.DateField(verbose_name='fecha limite')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='estado')),
                ('fecha_ejecucion', models.DateField(blank=True, null=True, verbose_name='fecha de ejecucion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_preventivas', to='companies.company', verbose_name='empresa')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_preventivas', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('no_conformidad_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_preventivas', to='corrective_actions.noconformidad', verbose_name='no conformidad de origen')),
            ],
            options={
                'verbose_name': 'accion preventiva',
                'verbose_name_plural': 'acciones preventivas',
                'ordering': ['fecha_limite', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccionCorrectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='descripcion de la accion')),
                ('fecha_limite', models.DateField(verbose_name='fecha limite')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='estado')),
                ('fecha_ejecucion', models.DateField(blank=True, null=True, verbose_name='fecha de ejecucion')),
                ('evidencia_implementacion', models.TextField(blank=True, verbose_name='evidencia de implementacion')),
                ('archivo_evidencia', models.FileField(blank=True, upload_to='corrective_actions/acciones/', verbose_name='archivo de evidencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_correctivas', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('no_conformidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_correctivas', to='corrective_actions.noconformidad', verbose_name='no conformidad')),
            ],
            options={
                'verbose_name': 'accion correctiva',
                'verbose_name_plural': 'acciones correctivas',
                'ordering': ['fecha_limite', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='noconformidad',
            index=models.Index(fields=['empresa', 'estado'], name='corrective__empresa_011241_idx'),
        ),
        migrations.AddIndex(
            model_name='noconformidad',
            index=models.Index(fields=['empresa', 'gravedad'], name='corrective__empresa_b511c6_idx'),
        ),
        migrations.AddIndex(
            model_name='noconformidad',
            index=models.Index(fields=['fecha_limite_resolucion'], name='corrective__fecha_l_c0fe3c_idx'),
        ),
        migrations.AddIndex(
            model_name='accionpreventiva',
            index=models.Index(fields=['empresa', 'estado'], name='corrective__empresa_42d5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='accionpreventiva',
            index=models.Index(fields=['fecha_limite'], name='corrective__fecha_l_e6fa71_idx'),
        ),
        migrations.AddIndex(
            model_name='accioncorrectiva',
            index=models.Index(fields=['no_conformidad', 'estado'], name='corrective__no_conf_298265_idx'),
        ),
        migrations.AddIndex(
            model_name='accioncorrectiva',
            index=models.Index(fields=['fecha_limite'], name='corrective__fecha_l_143138_idx'),
        ),
    ]
