# Generated by Django 6.0.5 on 2026-07-12 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_migrate_platform_admin_role'),
        ('workcenters', '0001_initial'),
        ('workers', '0004_alter_worker_national_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelRiesgoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.PositiveSmallIntegerField(help_text='Valor de 1 a 5 según la matriz INSST', unique=True, verbose_name='grado de riesgo (GR)')),
                ('probabilidad', models.PositiveSmallIntegerField(verbose_name='probabilidad')),
                ('severidad', models.PositiveSmallIntegerField(verbose_name='severidad')),
                ('nivel', models.CharField(max_length=20, verbose_name='nivel')),
                ('etiqueta', models.CharField(max_length=50, verbose_name='etiqueta')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='color hex')),
                ('color_fondo', models.CharField(default='#ffffff', max_length=7, verbose_name='color de fondo')),
                ('color_texto', models.CharField(default='#000000', max_length=7, verbose_name='color de texto')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'nivel de riesgo de referencia',
                'verbose_name_plural': 'niveles de riesgo de referencia',
                'ordering': ['grado'],
            },
        ),
        migrations.CreateModel(
            name='TipoPeligro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre del peligro')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('categoria', models.CharField(choices=[('mecanico', 'Mecánico'), ('quimico', 'Químico'), ('electrico', 'Eléctrico'), ('ergonomico', 'Ergonómico'), ('psicosocial', 'Psicosocial'), ('biologico', 'Biológico'), ('fisico', 'Físico'), ('locativo', 'Locativo (caídas, golpes)'), ('incendio', 'Incendio y explosión'), ('otro', 'Otro')], max_length=30, verbose_name='categoría')),
                ('referencia_normativa', models.CharField(blank=True, help_text='Ej: RD 1215/1997, RD 374/2001, Ley 31/1995', max_length=300, verbose_name='referencia normativa')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'tipo de peligro',
                'verbose_name_plural': 'tipos de peligro',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionRiesgos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='título de la evaluación')),
                ('fecha_evaluacion', models.DateField(verbose_name='fecha de evaluación')),
                ('fecha_proxima_revision', models.DateField(help_text='Art. 16 Ley 31/1995: revisiones periódicas obligatorias', verbose_name='fecha de próxima revisión')),
                ('metodologia', models.CharField(choices=[('propio', 'Riesgo propio'), ('comun', 'Riesgo común'), ('especifico', 'Específico del sector')], default='propio', max_length=20, verbose_name='método de evaluación')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='fecha de aprobación')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_aprobacion', 'Pendiente de aprobación'), ('aprobada', 'Aprobada'), ('en_revision', 'En revisión'), ('expirada', 'Expirada')], default='borrador', max_length=25, verbose_name='estado')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='versión')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='aprobado por')),
                ('centro_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_riesgos', to='workcenters.workcenter', verbose_name='centro de trabajo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_riesgos', to='companies.company', verbose_name='empresa')),
                ('revisado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='revisado por')),
            ],
            options={
                'verbose_name': 'evaluación de riesgos',
                'verbose_name_plural': 'evaluaciones de riesgos',
                'ordering': ['-fecha_evaluacion', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemEvaluacionRiesgos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_peligro', models.TextField(help_text='Descripción detallada del peligro identificado', verbose_name='descripción del peligro')),
                ('medidas_existentes', models.TextField(help_text='Medidas de protección y prevención actualmente implementadas', verbose_name='medidas preventivas existentes')),
                ('probabilidad', models.PositiveSmallIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], help_text='1=Baja, 2=Media, 3=Alta', verbose_name='probabilidad')),
                ('severidad', models.PositiveSmallIntegerField(choices=[(1, 'Ligeramente dañino'), (2, 'Dañino'), (3, 'Extremadamente dañino')], help_text='1=Ligeramente dañino, 2=Dañino, 3=Extremadamente dañino', verbose_name='severidad (consecuencias)')),
                ('grado_riesgo', models.PositiveSmallIntegerField(editable=False, help_text='Calculado automáticamente: Probabilidad × Severidad (escala 1-5)', verbose_name='grado de riesgo')),
                ('nivel_riesgo', models.CharField(choices=[('trivial', 'Trivial'), ('tolerable', 'Tolerable'), ('moderado', 'Moderado'), ('importante', 'Importante'), ('intolerable', 'Intolerable')], editable=False, max_length=20, verbose_name='nivel de riesgo')),
                ('medidas_propuestas', models.TextField(blank=True, help_text='Medidas a implementar para reducir el riesgo', verbose_name='nuevas medidas preventivas propuestas')),
                ('fecha_limite_implementacion', models.DateField(blank=True, null=True, verbose_name='fecha límite de implementación')),
                ('estado_implementacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('implementada', 'Implementada'), ('verificada', 'Verificada')], default='pendiente', max_length=20, verbose_name='estado de implementación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='risk_assessment.evaluacionriesgos', verbose_name='evaluación')),
                ('puesto_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_evaluacion', to='workers.jobposition', verbose_name='puesto de trabajo')),
                ('responsable_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='responsable de la medida')),
                ('tipo_peligro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_evaluacion', to='risk_assessment.tipopeligro', verbose_name='tipo de peligro')),
            ],
            options={
                'verbose_name': 'item de evaluación de riesgos',
                'verbose_name_plural': 'items de evaluación de riesgos',
                'ordering': ['evaluacion', 'puesto_trabajo', 'tipo_peligro'],
            },
        ),
    ]
