# Generated by Django 6.0.5 on 2026-07-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0002_crear_tipos_peligro_insst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemevaluacionriesgos',
            name='grado_riesgo',
            field=models.PositiveSmallIntegerField(editable=False, help_text='Calculado automáticamente: Probabilidad × Severidad (escala 1-9)', verbose_name='grado de riesgo'),
        ),
        migrations.AlterField(
            model_name='itemevaluacionriesgos',
            name='nivel_riesgo',
            field=models.CharField(choices=[('muy_bajo', 'Muy bajo'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('muy_alto', 'Muy alto')], editable=False, max_length=20, verbose_name='nivel de riesgo'),
        ),
        migrations.AlterField(
            model_name='itemevaluacionriesgos',
            name='severidad',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], help_text='1=Baja, 2=Media, 3=Alta', verbose_name='severidad'),
        ),
    ]
