# Generated by Django 6.0.4 on 2026-07-12 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0003_alter_itemevaluacionriesgos_grado_riesgo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemevaluacionriesgos',
            options={'ordering': ['evaluacion', 'puesto_trabajo', 'factor_riesgo_condicion'], 'verbose_name': 'item de evaluación de riesgos', 'verbose_name_plural': 'items de evaluación de riesgos'},
        ),
        migrations.RemoveField(
            model_name='itemevaluacionriesgos',
            name='descripcion_peligro',
        ),
        migrations.AddField(
            model_name='itemevaluacionriesgos',
            name='factor_riesgo_condicion',
            field=models.CharField(blank=True, default='', help_text='Ej: Ruido continuo en zona de producción, Iluminación deficiente en almacén', max_length=255, verbose_name='factor de riesgo / condición detectada'),
        ),
        migrations.AddField(
            model_name='itemevaluacionriesgos',
            name='riesgo',
            field=models.CharField(blank=True, choices=[('', '--- Seleccionar ---'), ('caidas_mismo_nivel', 'Caídas al mismo nivel'), ('caidas_distinto_nivel', 'Caídas a distinto nivel'), ('caida_objetos', 'Caída de objetos'), ('proyeccion_fragmentos', 'Proyección de fragmentos y/o partículas'), ('atrapamientos', 'Atrapamientos'), ('golpes', 'Golpes contra objetos'), ('cortes', 'Cortes y cortaduras'), ('quemaduras', 'Quemaduras'), ('electrocucion', 'Electrocución'), ('explosion', 'Explosión'), ('incendio', 'Incendio'), ('intoxicacion', 'Intoxicación'), ('asfixia', 'Asfixia'), ('ahogamiento', 'Ahogamiento'), ('sordera', 'Pérdida auditiva'), ('lesiones_osteomusculares', 'Lesiones osteomusculares'), ('enfermedad_profesional', 'Enfermedad profesional'), ('ergonomico', 'Riesgo ergonómico'), ('psicosocial', 'Riesgo psicosocial'), ('biologico', 'Riesgo biológico'), ('radiacion', 'Exposición a radiaciones'), ('derrame_sustancias', 'Derrame de sustancias'), ('otro', 'Otro')], help_text='Tipo de daño que puede producirse', max_length=50, verbose_name='riesgo'),
        ),
        migrations.AlterField(
            model_name='itemevaluacionriesgos',
            name='medidas_existentes',
            field=models.TextField(blank=True, help_text='Medidas de protección y prevención actualmente implementadas', verbose_name='medidas preventivas existentes'),
        ),
        migrations.AlterField(
            model_name='itemevaluacionriesgos',
            name='medidas_propuestas',
            field=models.TextField(blank=True, help_text='Medidas a implementar para reducir el riesgo', verbose_name='medidas preventivas propuestas'),
        ),
        migrations.AlterField(
            model_name='itemevaluacionriesgos',
            name='tipo_peligro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_evaluacion', to='risk_assessment.tipopeligro', verbose_name='tipo de peligro'),
        ),
    ]
