# Generated by Django 6.0.5 on 2026-07-13 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_migrate_platform_admin_role'),
        ('risk_assessment', '0004_add_factor_riesgo_condicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemevaluacionriesgos',
            name='frecuencia',
            field=models.CharField(blank=True, default='', help_text='Para riesgos monitorizables: ej. mensual, trimestral, anual', max_length=100, verbose_name='frecuencia de control'),
        ),
        migrations.AddField(
            model_name='itemevaluacionriesgos',
            name='tipo_riesgo',
            field=models.CharField(choices=[('evitable', 'Riesgo Evitable'), ('monitorizable', 'Riesgo Monitorizable'), ('no_evitable', 'Riesgo No Evitable')], default='evitable', max_length=20, verbose_name='tipo de riesgo'),
        ),
        migrations.CreateModel(
            name='InformeRiesgoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('higienico', 'Riesgos Higiénicos'), ('psicosocial', 'Riesgos Psicosociales'), ('ergonomico', 'Riesgos Ergonómicos')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='evaluacion_riesgos/especiales/')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_riesgos_especiales', to='companies.company')),
            ],
            options={
                'verbose_name': 'Informe de Riesgo Especial',
                'verbose_name_plural': 'Informes de Riesgos Especiales',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
