# Generated by Django 6.0.4 on 2026-07-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive_planning', '0002_add_medida_preventiva_catalogo'),
        ('risk_assessment', '0005_itemevaluacionriesgos_frecuencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemevaluacionriesgos',
            name='medidas_catalogo',
            field=models.ManyToManyField(blank=True, related_name='items_evaluacion', to='preventive_planning.medidapreventivacatalogo', verbose_name='medidas del catálogo'),
        ),
    ]
