# Generated by Django 6.0.4 on 2026-07-15 17:46

import apps.cae.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaCAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('documento', models.FileField(blank=True, null=True, upload_to=apps.cae.models.upload_carta_path, verbose_name='Carta de empresas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carta_cae', to='companies.company', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Carta CAE',
                'verbose_name_plural': 'Cartas CAE',
            },
        ),
        migrations.CreateModel(
            name='DocumentoCAETipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del documento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Tipo de documento CAE',
                'verbose_name_plural': 'Tipos de documentos CAE',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoRiesgosCAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('documento', models.FileField(blank=True, null=True, upload_to=apps.cae.models.upload_riesgos_path, verbose_name='Documento de riesgos, medidas preventivas y emergencia')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documento_riesgos_cae', to='companies.company', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Documento de Riesgos CAE',
                'verbose_name_plural': 'Documentos de Riesgos CAE',
            },
        ),
        migrations.CreateModel(
            name='EmpresaSubcontrata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('nombre_empresa', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('trabajo_realizar', models.TextField(verbose_name='Trabajo a realizar')),
                ('persona_contacto', models.CharField(max_length=200, verbose_name='Persona de contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electronico')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_subcontrata', to='companies.company', verbose_name='Empresa principal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Empresa subcontratada',
                'verbose_name_plural': 'Empresas subcontratadas',
                'ordering': ['nombre_empresa'],
            },
        ),
        migrations.CreateModel(
            name='ProcedimientoCAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('documento', models.FileField(blank=True, null=True, upload_to=apps.cae.models.upload_procedimiento_path, verbose_name='Procedimiento de coordinacion')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Version')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha del procedimiento')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procedimiento_cae', to='companies.company', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Procedimiento CAE',
                'verbose_name_plural': 'Procedimientos CAE',
            },
        ),
        migrations.CreateModel(
            name='DocumentoCAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('documento', models.FileField(blank=True, null=True, upload_to=apps.cae.models.upload_cae_path, verbose_name='Documento')),
                ('fecha_subida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de subida')),
                ('fecha_caducidad', models.DateField(blank=True, null=True, verbose_name='Fecha de caducidad')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='cae.documentocaetipo', verbose_name='Tipo de documento')),
                ('empresa_subcontrata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_cae', to='cae.empresasubcontrata', verbose_name='Empresa subcontratada')),
            ],
            options={
                'verbose_name': 'Documento CAE',
                'verbose_name_plural': 'Documentos CAE',
                'ordering': ['tipo_documento__orden', 'tipo_documento__nombre'],
                'unique_together': {('empresa_subcontrata', 'tipo_documento')},
            },
        ),
    ]
