# Generated by Django 6.0.4 on 2026-07-15 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaPreventivaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='nombre de la medida')),
                ('categoria', models.CharField(choices=[('mantenimiento_instalaciones', 'Mantenimiento de Instalaciones'), ('mantenimiento_equipos', 'Mantenimiento de Equipos'), ('entrega_epis', 'Entrega y Control de EPIs'), ('inspecciones', 'Inspecciones'), ('formacion', 'Formación y Capacitación'), ('vigilancia_salud', 'Vigilancia de la Salud'), ('limpieza_higiene', 'Limpieza y Higiene'), ('emergencias', 'Emergencias y Evacuación'), ('senalizacion_documentacion', 'Señalización y Documentación'), ('otros', 'Otros')], max_length=50, verbose_name='categoría')),
                ('frecuencia_por_defecto', models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('bienal', 'Bienal'), ('trienal', 'Trienal'), ('variable', 'Variable')], default='', max_length=20, verbose_name='frecuencia por defecto')),
                ('normativa', models.CharField(blank=True, default='', help_text='Ej: RD 1215/1997, Art. 16 Ley 31/1995', max_length=300, verbose_name='referencia normativa')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'medida preventiva del catálogo',
                'verbose_name_plural': 'catálogo de medidas preventivas',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemPlanificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito_puesto', models.CharField(blank=True, max_length=300, verbose_name='ambito / puesto de trabajo')),
                ('tipo_factor_riesgo', models.CharField(choices=[('evitables', 'Evitables'), ('monitorizables', 'Monitorizables'), ('no_evitables', 'No evitables')], default='evitables', max_length=20, verbose_name='tipo de factor de riesgo')),
                ('factor_riesgo', models.TextField(verbose_name='factor de riesgo')),
                ('detalle', models.TextField(blank=True, verbose_name='detalle')),
                ('riesgos', models.CharField(blank=True, choices=[('', '--- Seleccionar ---'), ('contactos_electricos', 'Contactos electricos'), ('caidas_mismo_nivel', 'Caídas al mismo nivel'), ('caidas_distinto_nivel', 'Caídas a distinto nivel'), ('caida_objetos', 'Caída de objetos'), ('proyeccion_fragmentos', 'Proyección de fragmentos y/o partículas'), ('atrapamientos', 'Atrapamientos'), ('golpes', 'Golpes contra objetos'), ('cortes', 'Cortes y cortaduras'), ('quemaduras', 'Quemaduras'), ('electrocucion', 'Electrocución'), ('explosion', 'Explosión'), ('incendio', 'Incendio'), ('intoxicacion', 'Intoxicación'), ('asfixia', 'Asfixia'), ('ahogamiento', 'Ahogamiento'), ('sordera', 'Pérdida auditiva'), ('lesiones_osteomusculares', 'Lesiones osteomusculares'), ('enfermedad_profesional', 'Enfermedad profesional'), ('ergonomico', 'Riesgo ergonómico'), ('psicosocial', 'Riesgo psicosocial'), ('biologico', 'Riesgo biológico'), ('radiacion', 'Exposición a radiaciones'), ('derrame_sustancias', 'Derrame de sustancias'), ('riesgos_profesionales', 'Riesgos no incluido en las listas sobre enfermedades profesionales'), ('otro', 'Otro')], max_length=60, verbose_name='riesgos')),
                ('pb', models.CharField(choices=[('B', 'Baja'), ('M', 'Media'), ('A', 'Alta'), ('NV', 'No valorada')], default='NV', max_length=2, verbose_name='probabilidad (PB)')),
                ('sv', models.CharField(choices=[('B', 'Baja'), ('M', 'Media'), ('A', 'Alta'), ('NV', 'No valorada')], default='NV', max_length=2, verbose_name='severidad (SV)')),
                ('gr', models.CharField(choices=[('B', 'Baja'), ('M', 'Media'), ('A', 'Alta'), ('NV', 'No valorada')], default='NV', max_length=2, verbose_name='grado de riesgo (GR)')),
                ('medidas_preventivas', models.TextField(blank=True, verbose_name='medidas preventivas (texto libre)')),
                ('detalle_medida', models.TextField(blank=True, verbose_name='detalle de la medida / accion correctora')),
                ('plazo_limite', models.CharField(blank=True, max_length=100, verbose_name='plazo limite')),
                ('fecha_objetivo', models.DateField(blank=True, null=True, verbose_name='fecha objetivo')),
                ('responsable', models.CharField(blank=True, max_length=200, verbose_name='responsable')),
                ('costes', models.CharField(blank=True, max_length=100, verbose_name='costes')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('implementada', 'Implementada'), ('verificada', 'Verificada'), ('continua', 'Continua')], default='pendiente', max_length=20, verbose_name='estado')),
                ('origen', models.CharField(blank=True, max_length=200, verbose_name='origen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_planificacion', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'item de planificacion preventiva',
                'verbose_name_plural': 'items de planificacion preventiva',
                'ordering': ['tipo_factor_riesgo', 'factor_riesgo'],
            },
        ),
    ]
