# Generated by Django 6.0.4 on 2026-07-15 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_migrate_platform_admin_role'),
        ('preventive_planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemplanificacion',
            name='medidas_preventivas',
            field=models.TextField(blank=True, verbose_name='medidas preventivas (texto libre)'),
        ),
        migrations.CreateModel(
            name='MedidaPreventivaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='nombre de la medida')),
                ('categoria', models.CharField(choices=[('mantenimiento_instalaciones', 'Mantenimiento de Instalaciones'), ('mantenimiento_equipos', 'Mantenimiento de Equipos'), ('entrega_epis', 'Entrega y Control de EPIs'), ('inspecciones', 'Inspecciones'), ('formacion', 'Formación y Capacitación'), ('vigilancia_salud', 'Vigilancia de la Salud'), ('limpieza_higiene', 'Limpieza y Higiene'), ('emergencias', 'Emergencias y Evacuación'), ('senalizacion_documentacion', 'Señalización y Documentación'), ('otros', 'Otros')], max_length=50, verbose_name='categoría')),
                ('frecuencia_por_defecto', models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('bienal', 'Bienal'), ('trienal', 'Trienal'), ('variable', 'Variable')], default='', max_length=20, verbose_name='frecuencia por defecto')),
                ('normativa', models.CharField(blank=True, default='', help_text='Ej: RD 1215/1997, Art. 16 Ley 31/1995', max_length=300, verbose_name='referencia normativa')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('company', models.ForeignKey(blank=True, help_text='Vacío = catálogo global del sistema. Con valor = medida personalizada de la empresa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medidas_preventivas_propias', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'medida preventiva del catálogo',
                'verbose_name_plural': 'catálogo de medidas preventivas',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='itemplanificacion',
            name='medidas_catalogo',
            field=models.ManyToManyField(blank=True, related_name='items_planificacion', to='preventive_planning.medidapreventivacatalogo', verbose_name='medidas del catálogo'),
        ),
        migrations.AddIndex(
            model_name='medidapreventivacatalogo',
            index=models.Index(fields=['categoria', 'activo'], name='preventive__categor_15fc6c_idx'),
        ),
        migrations.AddIndex(
            model_name='medidapreventivacatalogo',
            index=models.Index(fields=['company', 'activo'], name='preventive__company_dea24e_idx'),
        ),
    ]
