# Generated by Django 6.0.4 on 2026-07-15 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('preventive_planning', '0001_initial'),
        ('risk_assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemplanificacion',
            name='evaluacion_riesgos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_planificacion', to='risk_assessment.evaluacionriesgos', verbose_name='evaluacion de riesgos'),
        ),
        migrations.AddField(
            model_name='itemplanificacion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='medidapreventivacatalogo',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Vacío = catálogo global del sistema. Con valor = medida personalizada de la empresa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medidas_preventivas_propias', to='companies.company', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='medidapreventivacatalogo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='medidapreventivacatalogo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='itemplanificacion',
            name='medidas_catalogo',
            field=models.ManyToManyField(blank=True, related_name='items_planificacion', to='preventive_planning.medidapreventivacatalogo', verbose_name='medidas del catálogo'),
        ),
        migrations.AddIndex(
            model_name='medidapreventivacatalogo',
            index=models.Index(fields=['categoria', 'activo'], name='preventive__categor_15fc6c_idx'),
        ),
        migrations.AddIndex(
            model_name='medidapreventivacatalogo',
            index=models.Index(fields=['company', 'activo'], name='preventive__company_dea24e_idx'),
        ),
        migrations.AddIndex(
            model_name='itemplanificacion',
            index=models.Index(fields=['empresa', 'estado'], name='preventive__empresa_f09671_idx'),
        ),
        migrations.AddIndex(
            model_name='itemplanificacion',
            index=models.Index(fields=['empresa', 'tipo_factor_riesgo'], name='preventive__empresa_e54823_idx'),
        ),
    ]
