# Generated by Django 6.0.5 on 2026-07-14 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_migrate_platform_admin_role'),
        ('corrective_actions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormativaLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='nombre / título')),
                ('tipo', models.CharField(choices=[('ley', 'Ley'), ('real_decreto', 'Real Decreto'), ('rd_to', 'Real Decreto - Texto Ordinado'), ('orden', 'Orden Ministerial'), ('instruccion', 'Instrucción'), ('reglamento', 'Reglamento'), ('ntp', 'Nota Técnica de Prevención'), ('otra', 'Otra normativa')], max_length=30, verbose_name='tipo de normativa')),
                ('numero', models.CharField(blank=True, default='', help_text='ej: 31/1995, 39/1997', max_length=100, verbose_name='número / referencia')),
                ('ambito', models.CharField(choices=[('estatal', 'Estatal'), ('autonomico', 'Autonómico'), ('local', 'Local'), ('europeo', 'Europeo'), ('internacional', 'Internacional')], default='estatal', max_length=30, verbose_name='ámbito')),
                ('comunidad_autonoma', models.CharField(blank=True, default='', help_text='Solo si es normativa autonómica', max_length=100, verbose_name='comunidad autónoma')),
                ('fecha_publicacion', models.DateField(blank=True, null=True, verbose_name='fecha de publicación')),
                ('fecha_vigencia', models.DateField(blank=True, null=True, verbose_name='fecha de entrada en vigor')),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True, verbose_name='fecha fin de vigencia')),
                ('boe_enlace', models.URLField(blank=True, default='', help_text='Enlace al texto completo en BOE o fuente oficial', verbose_name='enlace BOE / normativa')),
                ('resumen', models.TextField(blank=True, default='', help_text='Resumen de las principales disposiciones', verbose_name='resumen')),
                ('activa', models.BooleanField(default=True, verbose_name='normativa activa')),
                ('notas_internas', models.TextField(blank=True, default='', verbose_name='notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'normativa legal',
                'verbose_name_plural': 'normativa legal',
                'ordering': ['-fecha_publicacion', 'numero'],
                'indexes': [models.Index(fields=['tipo', 'activa'], name='legal_requi_tipo_e463ab_idx'), models.Index(fields=['ambito'], name='legal_requi_ambito_182940_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequisitoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='título del requisito')),
                ('descripcion', models.TextField(verbose_name='descripción / obligación legal')),
                ('categoria', models.CharField(choices=[('prevencion', 'Prevención de riesgos'), ('formacion', 'Formación y capacitación'), ('vigilancia', 'Vigilancia de la salud'), ('epis', 'EPIs y seguridad'), ('instalaciones', 'Instalaciones y equipos'), ('emergencias', 'Emergencias y evacuación'), ('documentacion', 'Documentación'), ('notificacion', 'Notificación a autoridades'), ('otros', 'Otros requisitos')], default='prevencion', max_length=30, verbose_name='categoría')),
                ('articulo', models.CharField(blank=True, default='', max_length=100, verbose_name='artículo / apartado')),
                ('plazo_cumplimiento', models.CharField(blank=True, default='', help_text='ej: Permanente, 6 meses, A partir de la publicación', max_length=200, verbose_name='plazo de cumplimiento')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('normativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='legal_requirements.normativalegal', verbose_name='normativa')),
            ],
            options={
                'verbose_name': 'requisito legal',
                'verbose_name_plural': 'requisitos legales',
                'ordering': ['normativa', 'articulo', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='CumplimientoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('cumple', 'Cumple'), ('no_cumple', 'No cumple'), ('en_curso', 'En curso de cumplimiento'), ('no_aplica', 'No aplica'), ('pendiente', 'Pendiente de evaluación')], default='pendiente', max_length=20, verbose_name='estado de cumplimiento')),
                ('fecha_evaluacion', models.DateField(blank=True, null=True, verbose_name='fecha de evaluación')),
                ('fecha_proxima_revision', models.DateField(blank=True, null=True, verbose_name='próxima revisión')),
                ('evidencia', models.TextField(blank=True, default='', help_text='Documentos, registros, acciones que acreditan el cumplimiento', verbose_name='evidencia de cumplimiento')),
                ('acciones_necesarias', models.TextField(blank=True, default='', verbose_name='acciones necesarias para cumplir')),
                ('notas', models.TextField(blank=True, default='', verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumplimientos_legales', to='companies.company', verbose_name='empresa')),
                ('evaluado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cumplimientos_evaluados', to=settings.AUTH_USER_MODEL, verbose_name='evaluado por')),
                ('nc_generada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cumplimiento_legal', to='corrective_actions.noconformidad', verbose_name='NC generada')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cumplimientos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumplimientos', to='legal_requirements.requisitolegal', verbose_name='requisito legal')),
            ],
            options={
                'verbose_name': 'cumplimiento legal',
                'verbose_name_plural': 'cumplimientos legales',
                'ordering': ['empresa', 'requisito'],
            },
        ),
        migrations.CreateModel(
            name='AlertaLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vencimiento', 'Vencimiento de revisión'), ('cambio_normativo', 'Cambio normativo'), ('no_cumplimiento', 'No cumplimiento detectado'), ('recordatorio', 'Recordatorio')], max_length=30, verbose_name='tipo de alerta')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('leida', models.BooleanField(default=False, verbose_name='leída')),
                ('resuelta', models.BooleanField(default=False, verbose_name='resuelta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_legales', to='companies.company', verbose_name='empresa')),
                ('cumplimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='legal_requirements.cumplimientolegal', verbose_name='cumplimiento relacionado')),
                ('normativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='legal_requirements.normativalegal', verbose_name='normativa relacionada')),
            ],
            options={
                'verbose_name': 'alerta legal',
                'verbose_name_plural': 'alertas legales',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['empresa', 'leida'], name='legal_requi_empresa_70365d_idx'), models.Index(fields=['empresa', 'resuelta'], name='legal_requi_empresa_844de4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='requisitolegal',
            index=models.Index(fields=['normativa', 'categoria'], name='legal_requi_normati_6e3695_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitolegal',
            index=models.Index(fields=['categoria'], name='legal_requi_categor_b2d8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='cumplimientolegal',
            index=models.Index(fields=['empresa', 'estado'], name='legal_requi_empresa_1237bc_idx'),
        ),
        migrations.AddIndex(
            model_name='cumplimientolegal',
            index=models.Index(fields=['empresa', 'fecha_proxima_revision'], name='legal_requi_empresa_65407c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cumplimientolegal',
            unique_together={('empresa', 'requisito')},
        ),
    ]
