# Generated by Django 6.0.5 on 2026-05-09 05:26

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='slug')),
                ('scope', models.CharField(choices=[('general', 'General'), ('company', 'Empresa'), ('workcenter', 'Centro de trabajo'), ('worker', 'Trabajador'), ('job_position', 'Puesto de trabajo')], default='general', max_length=30, verbose_name='ámbito')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='obligatorio')),
                ('default_validity_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='validez por defecto (días)')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'categoría documental',
                'verbose_name_plural': 'categorías documentales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path, verbose_name='archivo')),
                ('version', models.CharField(default='1.0', max_length=50, verbose_name='versión')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='código documental')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='fecha de emisión')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='fecha de revisión')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='fecha de caducidad')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('valid', 'Vigente'), ('expired', 'Caducado'), ('revoked', 'Revocado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='estado')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='confidencial')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='id del objeto')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company', verbose_name='empresa')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='tipo de objeto')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentcategory', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
