# Generated by Django 6.0.4 on 2026-07-15 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_migrate_platform_admin_role'),
        ('workers', '0004_alter_worker_national_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='nombre del requisito')),
                ('tipo', models.CharField(choices=[('equipo', 'Equipo de trabajo'), ('trabajo', 'Trabajo o actividad')], max_length=20, verbose_name='tipo')),
                ('categoria', models.CharField(blank=True, default='', help_text='Agrupación libre: Maquinaria, Trabajos especiales, etc.', max_length=100, verbose_name='categoría')),
                ('normativa', models.CharField(blank=True, default='', help_text='Ej: RD 1215/1997, RD 2177/2004', max_length=300, verbose_name='referencia normativa')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('empresa', models.ForeignKey(blank=True, help_text='Vacío = catálogo global del sistema', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_autorizacion', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'requisito de autorización',
                'verbose_name_plural': 'requisitos de autorización',
                'ordering': ['tipo', 'categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AutorizacionTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_autorizacion', models.DateField(verbose_name='fecha de autorización')),
                ('fecha_caducidad', models.DateField(blank=True, help_text='Dejar vacío si no caduca', null=True, verbose_name='fecha de caducidad')),
                ('entidad_emisora', models.CharField(blank=True, default='', help_text='Ej: INSST, AENOR, empresa formativa', max_length=200, verbose_name='entidad emisora')),
                ('numero_certificado', models.CharField(blank=True, default='', max_length=100, verbose_name='número de certificado')),
                ('archivo', models.FileField(blank=True, upload_to='autorizaciones/', verbose_name='certificado / acreditación')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='observaciones')),
                ('activa', models.BooleanField(default=True, verbose_name='autorización activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones_trabajadores', to='companies.company', verbose_name='empresa')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='workers.worker', verbose_name='trabajador')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='authorizations.requisitoautorizacion', verbose_name='requisito')),
            ],
            options={
                'verbose_name': 'autorización de trabajador',
                'verbose_name_plural': 'autorizaciones de trabajadores',
                'ordering': ['requisito', 'trabajador'],
            },
        ),
        migrations.AddIndex(
            model_name='requisitoautorizacion',
            index=models.Index(fields=['empresa', 'activo'], name='authorizati_empresa_424ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitoautorizacion',
            index=models.Index(fields=['tipo', 'activo'], name='authorizati_tipo_3e9a54_idx'),
        ),
        migrations.AddIndex(
            model_name='autorizaciontrabajador',
            index=models.Index(fields=['empresa', 'activa'], name='authorizati_empresa_9c8c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='autorizaciontrabajador',
            index=models.Index(fields=['trabajador', 'activa'], name='authorizati_trabaja_613cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='autorizaciontrabajador',
            index=models.Index(fields=['fecha_caducidad'], name='authorizati_fecha_c_122ef5_idx'),
        ),
        migrations.AddConstraint(
            model_name='autorizaciontrabajador',
            constraint=models.UniqueConstraint(fields=('trabajador', 'requisito', 'fecha_autorizacion'), name='uniq_autorizacion_trab_req_fecha'),
        ),
    ]
