# Generated by Django 6.0.4 on 2026-07-12 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_migrate_platform_admin_role'),
        ('corrective_actions', '0001_initial'),
        ('workcenters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripcion')),
                ('categoria', models.CharField(choices=[('seguridad', 'Seguridad'), ('salud', 'Salud laboral'), ('medio_ambiente', 'Medio ambiente'), ('maquinaria', 'Maquinaria'), ('instalaciones', 'Instalaciones'), ('epi', 'EPIs'), ('otro', 'Otro')], default='seguridad', max_length=20, verbose_name='categoria')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_inspeccion', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'plantilla de inspeccion',
                'verbose_name_plural': 'plantillas de inspeccion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inspeccion', models.DateField(verbose_name='fecha de inspeccion')),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_curso', 'En curso'), ('completada', 'Completada'), ('con_nc', 'Con no conformidades')], default='planificada', max_length=20, verbose_name='estado')),
                ('resultado_general', models.CharField(blank=True, choices=[('conforme', 'Conforme'), ('no_conforme', 'No conforme'), ('parcial', 'Parcialmente conforme')], max_length=20, verbose_name='resultado general')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('fotos', models.FileField(blank=True, upload_to='inspecciones/fotos/', verbose_name='fotos evidencia')),
                ('nc_generadas', models.BooleanField(default=False, verbose_name='NCs generadas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='workcenters.workcenter', verbose_name='centro de trabajo')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='companies.company', verbose_name='empresa')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='inspector')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones', to='inspections.plantillainspeccion', verbose_name='plantilla')),
            ],
            options={
                'verbose_name': 'inspeccion',
                'verbose_name_plural': 'inspecciones',
                'ordering': ['-fecha_inspeccion', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaInspeccionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('descripcion', models.TextField(verbose_name='que se inspecciona')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.plantillainspeccion', verbose_name='plantilla')),
            ],
            options={
                'verbose_name': 'item de plantilla',
                'verbose_name_plural': 'items de plantilla',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ItemInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('descripcion', models.TextField(verbose_name='que se inspecciona')),
                ('resultado', models.CharField(blank=True, choices=[('conforme', 'Conforme'), ('no_conforme', 'No conforme'), ('na', 'No aplica')], max_length=20, verbose_name='resultado')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('foto', models.FileField(blank=True, upload_to='inspecciones/items/', verbose_name='foto evidencia')),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.inspeccion', verbose_name='inspeccion')),
                ('no_conformidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_inspeccion', to='corrective_actions.noconformidad', verbose_name='no conformidad generada')),
            ],
            options={
                'verbose_name': 'item de inspeccion',
                'verbose_name_plural': 'items de inspeccion',
                'ordering': ['orden'],
                'indexes': [models.Index(fields=['inspeccion', 'resultado'], name='inspections_inspecc_8d1c13_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inspeccion',
            index=models.Index(fields=['empresa', 'estado'], name='inspections_empresa_b5ae22_idx'),
        ),
        migrations.AddIndex(
            model_name='inspeccion',
            index=models.Index(fields=['empresa', 'centro_trabajo'], name='inspections_empresa_0419f8_idx'),
        ),
        migrations.AddIndex(
            model_name='inspeccion',
            index=models.Index(fields=['fecha_inspeccion'], name='inspections_fecha_i_d0e5de_idx'),
        ),
    ]
