# Generated by Django 6.0.4 on 2026-07-15 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('workcenters', '0001_initial'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnfermedadProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='codigo')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('fecha_diagnostico', models.DateField(verbose_name='fecha de diagnostico')),
                ('nombre_enfermedad', models.CharField(max_length=300, verbose_name='nombre de la enfermedad')),
                ('agente_causante', models.CharField(choices=[('quimico', 'Quimico'), ('biologico', 'Biologico'), ('fisico', 'Fisico'), ('ergonomico', 'Ergonomico'), ('psicosocial', 'Psicosocial'), ('mixto', 'Mixto'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='agente causante')),
                ('tipo_exposicion', models.CharField(blank=True, max_length=300, verbose_name='tipo de exposicion')),
                ('duracion_exposicion', models.CharField(blank=True, max_length=100, verbose_name='duracion de la exposicion')),
                ('parte_cuerpo', models.CharField(blank=True, max_length=200, verbose_name='parte del cuerpo afectada')),
                ('gravedad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave'), ('muy_grave', 'Muy grave')], default='leve', max_length=20, verbose_name='gravedad')),
                ('descripcion', models.TextField(verbose_name='descripcion de la enfermedad')),
                ('testigos', models.TextField(blank=True, verbose_name='testigos')),
                ('notify_salud', models.BooleanField(default=False, verbose_name='notificado a vigilancia de la salud')),
                ('notify_inspeccion', models.BooleanField(default=False, verbose_name='notificado a inspeccion de trabajo')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_investigacion', 'En investigacion'), ('cerrado', 'Cerrado')], default='abierto', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermedades_profesionales', to='workcenters.workcenter', verbose_name='centro de trabajo')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfermedades_profesionales_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermedades_profesionales', to='companies.company', verbose_name='empresa')),
                ('trabajador_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfermedades_profesionales', to='workers.worker', verbose_name='trabajador afectado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'enfermedad profesional',
                'verbose_name_plural': 'enfermedades profesionales',
                'ordering': ['-fecha_diagnostico', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigacionEEPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('metodologia', models.CharField(choices=[('_5_porques', '5 Porques'), ('ishikawa', 'Ishikawa (Espina de pez)'), ('arbol_causas', 'Arbol de causas'), ('otro', 'Otro')], default='_5_porques', max_length=20, verbose_name='metodologia de analisis')),
                ('puesto_trabajo', models.CharField(blank=True, max_length=200, verbose_name='puesto de trabajo')),
                ('horas_trabajador', models.PositiveIntegerField(blank=True, null=True, verbose_name='horas trabajadas (1-8)')),
                ('hora_dia', models.TimeField(blank=True, null=True, verbose_name='hora del dia')),
                ('edad', models.PositiveIntegerField(blank=True, null=True, verbose_name='edad del trabajador')),
                ('tiempo_puesto', models.CharField(blank=True, max_length=100, verbose_name='tiempo en el puesto de trabajo')),
                ('acto_condicion_detectada', models.TextField(blank=True, verbose_name='acto o condicion detectada')),
                ('riesgo_identificado', models.CharField(blank=True, choices=[('', '--- Seleccionar ---'), ('sordera', 'Pérdida auditiva (sordera)'), ('vibracion_manos', 'Síndrome del brazo por vibración'), ('lesiones_osteomusculares', 'Lesiones osteomusculares (TME)'), ('dermatitis', 'Dermatitis de contacto'), ('asma_laboral', 'Asma laboral'), ('cancer', 'Cancer profesional'), ('intoxicacion_cronica', 'Intoxicacion cronica'), ('silicosis', 'Silicosis'), ('asbestosis', 'Asbestosis (amianto)'), ('sordera_ruido', 'Hipoacusia por ruido'), ('tendinitis', 'Tendinitis'), ('hernia_discal', 'Hernia discal lumbar'), ('stress_laboral', 'Stress laboral'), ('burnout', 'Burnout'), ('agresion_psicologica', 'Agresion psicologica'), ('otro', 'Otro')], max_length=40, verbose_name='riesgo identificado')),
                ('medidas_preventivas', models.TextField(blank=True, verbose_name='medidas preventivas propuestas')),
                ('plazo', models.DateField(blank=True, null=True, verbose_name='plazo de implantacion')),
                ('coste', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='coste estimado')),
                ('riesgo_en_er', models.BooleanField(default=False, verbose_name='riesgo en evaluacion de riesgos')),
                ('descripcion_ideal', models.TextField(blank=True, verbose_name='descripcion de lo que deberia haber pasado')),
                ('descripcion_real', models.TextField(blank=True, verbose_name='descripcion de lo que realmente paso')),
                ('causas_inmediatas', models.TextField(blank=True, verbose_name='causas inmediatas')),
                ('causas_basicas', models.TextField(blank=True, verbose_name='causas basicas')),
                ('causas_organizativas', models.TextField(blank=True, verbose_name='causas organizativas')),
                ('conclusiones', models.TextField(blank=True, verbose_name='conclusiones')),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('completada', 'Completada')], default='en_curso', max_length=20, verbose_name='estado')),
                ('fecha_firma', models.DateField(blank=True, null=True, verbose_name='fecha de firma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('enfermedad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigacion', to='epps.enfermedadprofesional', verbose_name='enfermedad profesional')),
                ('investigador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigaciones_eepp', to=settings.AUTH_USER_MODEL, verbose_name='investigador')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigaciones_epp_responsable', to=settings.AUTH_USER_MODEL, verbose_name='responsable de medidas')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigaciones_eepp_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='revisor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'investigacion de enfermedad profesional',
                'verbose_name_plural': 'investigaciones de enfermedades profesionales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ProcedimientoInvestigacionEEPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripcion')),
                ('archivo', models.FileField(upload_to='eepp/procedimientos/', verbose_name='archivo del procedimiento')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='version')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_investigacion_eepp', to='companies.company', verbose_name='empresa')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimientos_investigacion_eepp', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'procedimiento de investigacion EEPP',
                'verbose_name_plural': 'procedimientos de investigacion EEPP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='enfermedadprofesional',
            index=models.Index(fields=['empresa', 'estado'], name='epps_enferm_empresa_29b310_idx'),
        ),
        migrations.AddIndex(
            model_name='enfermedadprofesional',
            index=models.Index(fields=['empresa', 'centro_trabajo'], name='epps_enferm_empresa_8901c2_idx'),
        ),
        migrations.AddIndex(
            model_name='enfermedadprofesional',
            index=models.Index(fields=['fecha_diagnostico'], name='epps_enferm_fecha_d_70a763_idx'),
        ),
    ]
