# Generated by Django 6.0.5 on 2026-07-13 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_migrate_platform_admin_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoQuimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fabricante', models.CharField(blank=True, default='', max_length=200)),
                ('composicion', models.TextField(blank=True, default='')),
                ('uso', models.TextField(blank=True, default='')),
                ('ubicacion', models.CharField(blank=True, default='', max_length=200)),
                ('ficha_seguridad', models.FileField(blank=True, upload_to='fichas_seguridad/')),
                ('imagen_etiqueta', models.ImageField(blank=True, upload_to='etiquetas_quimicos/')),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidad', models.CharField(blank=True, default='uds', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_quimicos', to='companies.company')),
            ],
            options={
                'verbose_name': 'Producto Químico',
                'verbose_name_plural': 'Productos Químicos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClasificacionQuimica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictograma', models.CharField(choices=[('GHS01', 'Explosivo'), ('GHS02', 'Inflamable'), ('GHS03', 'Comburente'), ('GHS04', 'Gases a presión'), ('GHS05', 'Corrosivo'), ('GHS06', 'Tóxico'), ('GHS07', 'Irritante / Nocivo'), ('GHS08', 'Peligro para la salud'), ('GHS09', 'Peligro para el medio ambiente')], max_length=10)),
                ('frase_riesgo', models.CharField(blank=True, default='', max_length=200)),
                ('frase_precaucion', models.CharField(blank=True, default='', max_length=200)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='chemical_products.productoquimico')),
            ],
            options={
                'verbose_name': 'Clasificación Química',
                'verbose_name_plural': 'Clasificaciones Químicas',
            },
        ),
    ]
