# Generated by Django 6.0.4 on 2026-07-15 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('categoria', models.CharField(choices=[('cabeza', 'Proteccion de la cabeza'), ('manos', 'Proteccion de las manos'), ('pies', 'Proteccion de los pies'), ('ojos', 'Proteccion ocular'), ('oidos', 'Proteccion auditiva'), ('respiratoria', 'Proteccion respiratoria'), ('corporal', 'Proteccion corporal'), ('otro', 'Otro')], default='cabeza', max_length=20, verbose_name='categoria')),
                ('riesgos_proteccion', models.TextField(help_text='Describe los riesgos frente a los que protege este EPI.', verbose_name='riesgos que protege')),
                ('norma_eu', models.CharField(help_text='Norma europea que debe cumplir (ej: EN 166, EN 388, EN ISO 20345).', max_length=100, verbose_name='norma UNE / EN')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripcion')),
                ('imagen', models.FileField(blank=True, upload_to='epis/catalogo/', verbose_name='imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'catalogo de EPI',
                'verbose_name_plural': 'catalogo de EPIs',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='numero de serie')),
                ('vida_util_meses', models.PositiveIntegerField(default=12, verbose_name='vida util (meses)')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio unitario')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='proveedor')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='fecha de compra')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('en_mantenimiento', 'En mantenimiento'), ('retirado', 'Retirado')], default='disponible', max_length=20, verbose_name='estado')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epis', to='epis.catalogoepi', verbose_name='catalogo de EPI')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis', to='companies.company', verbose_name='empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'EPI',
                'verbose_name_plural': 'EPIs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntregaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(verbose_name='fecha de entrega')),
                ('fecha_caducidad', models.DateField(blank=True, null=True, verbose_name='fecha de caducidad')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto'), ('caducado', 'Caducado'), ('reemplazado', 'Reemplazado')], default='activo', max_length=20, verbose_name='estado')),
                ('motivo_devolucion', models.TextField(blank=True, verbose_name='motivo de devolucion')),
                ('firma_trabajador', models.BooleanField(default=False, verbose_name='firma del trabajador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_epi', to='companies.company', verbose_name='empresa')),
                ('entregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_epi_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='entregado por')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_epi', to='workers.worker', verbose_name='trabajador')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='epis.epi', verbose_name='EPI')),
            ],
            options={
                'verbose_name': 'entrega de EPI',
                'verbose_name_plural': 'entregas de EPI',
                'ordering': ['-fecha_entrega', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FirmaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_firma', models.CharField(choices=[('pendiente', 'Pendiente de firma'), ('firmado', 'Firmado'), ('no_aplica', 'No aplica')], default='pendiente', max_length=20, verbose_name='estado de firma')),
                ('archivo_firmado', models.FileField(blank=True, upload_to='epis/firmas/', verbose_name='acuse firmado (PDF)')),
                ('fecha_firma', models.DateField(blank=True, null=True, verbose_name='fecha de firma')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas_epi', to='companies.company', verbose_name='empresa')),
                ('entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma', to='epis.entregaepi', verbose_name='entrega')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas_epi', to='workers.worker', verbose_name='trabajador')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'firma de entrega de EPI',
                'verbose_name_plural': 'firmas de entrega de EPI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspeccionEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('fecha', models.DateField(verbose_name='fecha de inspeccion')),
                ('resultado', models.CharField(choices=[('bueno', 'Buen estado'), ('regular', 'Estado regular'), ('malo', 'Mal estado'), ('rechazado', 'Rechazado')], default='bueno', max_length=20, verbose_name='resultado')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones_epi', to='companies.company', verbose_name='empresa')),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones', to='epis.entregaepi', verbose_name='entrega asociada')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='epis.epi', verbose_name='EPI')),
                ('inspeccionado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones_epi_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='inspeccionado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'inspeccion de EPI',
                'verbose_name_plural': 'inspecciones de EPI',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcedimientoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripcion')),
                ('archivo', models.FileField(upload_to='epis/procedimientos/', verbose_name='archivo del procedimiento')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='version')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_epi', to='companies.company', verbose_name='empresa')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimientos_epi', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'procedimiento de entrega de EPI',
                'verbose_name_plural': 'procedimientos de entrega de EPI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='epi',
            index=models.Index(fields=['empresa', 'estado'], name='epis_epi_empresa_b202f7_idx'),
        ),
        migrations.AddIndex(
            model_name='epi',
            index=models.Index(fields=['empresa', 'catalogo'], name='epis_epi_empresa_dd56b8_idx'),
        ),
        migrations.AddIndex(
            model_name='entregaepi',
            index=models.Index(fields=['empresa', 'estado'], name='epis_entreg_empresa_767a99_idx'),
        ),
        migrations.AddIndex(
            model_name='entregaepi',
            index=models.Index(fields=['empresa', 'trabajador'], name='epis_entreg_empresa_92d419_idx'),
        ),
        migrations.AddIndex(
            model_name='entregaepi',
            index=models.Index(fields=['fecha_caducidad'], name='epis_entreg_fecha_c_70a7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='firmaentrega',
            index=models.Index(fields=['empresa', 'estado_firma'], name='epis_firmae_empresa_89745a_idx'),
        ),
        migrations.AddIndex(
            model_name='firmaentrega',
            index=models.Index(fields=['empresa', 'trabajador'], name='epis_firmae_empresa_08c800_idx'),
        ),
        migrations.AddIndex(
            model_name='inspeccionepi',
            index=models.Index(fields=['empresa', 'resultado'], name='epis_inspec_empresa_637f9c_idx'),
        ),
        migrations.AddIndex(
            model_name='inspeccionepi',
            index=models.Index(fields=['fecha'], name='epis_inspec_fecha_fc4582_idx'),
        ),
    ]
