# Generated by Django 6.0.5 on 2026-07-13 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_migrate_platform_admin_role'),
        ('workers', '0004_alter_worker_national_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='numero de serie')),
                ('vida_util_meses', models.PositiveIntegerField(default=12, verbose_name='vida util (meses)')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio unitario')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='proveedor')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='fecha de compra')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('en_mantenimiento', 'En mantenimiento'), ('retirado', 'Retirado')], default='disponible', max_length=20, verbose_name='estado')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'EPI',
                'verbose_name_plural': 'EPIs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntregaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(verbose_name='fecha de entrega')),
                ('fecha_caducidad', models.DateField(blank=True, null=True, verbose_name='fecha de caducidad')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto'), ('caducado', 'Caducado'), ('reemplazado', 'Reemplazado')], default='activo', max_length=20, verbose_name='estado')),
                ('motivo_devolucion', models.TextField(blank=True, verbose_name='motivo de devolucion')),
                ('firma_trabajador', models.BooleanField(default=False, verbose_name='firma del trabajador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_epi', to='companies.company', verbose_name='empresa')),
                ('entregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_epi_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='entregado por')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_epi', to='workers.worker', verbose_name='trabajador')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='epis.epi', verbose_name='EPI')),
            ],
            options={
                'verbose_name': 'entrega de EPI',
                'verbose_name_plural': 'entregas de EPI',
                'ordering': ['-fecha_entrega', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspeccionEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha de inspeccion')),
                ('resultado', models.CharField(choices=[('bueno', 'Buen estado'), ('regular', 'Estado regular'), ('malo', 'Mal estado'), ('rechazado', 'Rechazado')], default='bueno', max_length=20, verbose_name='resultado')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones_epi', to='companies.company', verbose_name='empresa')),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones', to='epis.entregaepi', verbose_name='entrega asociada')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='epis.epi', verbose_name='EPI')),
                ('inspeccionado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones_epi_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='inspeccionado por')),
            ],
            options={
                'verbose_name': 'inspeccion de EPI',
                'verbose_name_plural': 'inspecciones de EPI',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipoEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('categoria', models.CharField(choices=[('cabeza', 'Proteccion de la cabeza'), ('manos', 'Proteccion de las manos'), ('pies', 'Proteccion de los pies'), ('ojos', 'Proteccion ocular'), ('oidos', 'Proteccion auditiva'), ('respiratoria', 'Proteccion respiratoria'), ('corporal', 'Proteccion corporal'), ('antisimia', 'Proteccion antimotin'), ('otro', 'Otro')], default='cabeza', max_length=20, verbose_name='categoria')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripcion / uso recomendado')),
                ('imagen', models.FileField(blank=True, upload_to='epis/tipos/', verbose_name='imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_epi', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'tipo de EPI',
                'verbose_name_plural': 'tipos de EPI',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='epi',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis', to='epis.tipoepi', verbose_name='tipo de EPI'),
        ),
        migrations.AddIndex(
            model_name='entregaepi',
            index=models.Index(fields=['empresa', 'estado'], name='epis_entreg_empresa_767a99_idx'),
        ),
        migrations.AddIndex(
            model_name='entregaepi',
            index=models.Index(fields=['empresa', 'trabajador'], name='epis_entreg_empresa_92d419_idx'),
        ),
        migrations.AddIndex(
            model_name='entregaepi',
            index=models.Index(fields=['fecha_caducidad'], name='epis_entreg_fecha_c_70a7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='inspeccionepi',
            index=models.Index(fields=['empresa', 'resultado'], name='epis_inspec_empresa_637f9c_idx'),
        ),
        migrations.AddIndex(
            model_name='inspeccionepi',
            index=models.Index(fields=['fecha'], name='epis_inspec_fecha_fc4582_idx'),
        ),
        migrations.AddIndex(
            model_name='epi',
            index=models.Index(fields=['empresa', 'estado'], name='epis_epi_empresa_b202f7_idx'),
        ),
        migrations.AddIndex(
            model_name='epi',
            index=models.Index(fields=['empresa', 'tipo'], name='epis_epi_empresa_e16b55_idx'),
        ),
    ]
