# Generated by Django 6.0.5 on 2026-07-13 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_migrate_platform_admin_role'),
        ('epis', '0001_initial'),
        ('workers', '0004_alter_worker_national_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimientoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripcion')),
                ('archivo', models.FileField(upload_to='epis/procedimientos/', verbose_name='archivo del procedimiento')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='version')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_epi', to='companies.company', verbose_name='empresa')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimientos_epi', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
            ],
            options={
                'verbose_name': 'procedimiento de entrega de EPI',
                'verbose_name_plural': 'procedimientos de entrega de EPI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FirmaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_firma', models.CharField(choices=[('pendiente', 'Pendiente de firma'), ('firmado', 'Firmado'), ('no_aplica', 'No aplica')], default='pendiente', max_length=20, verbose_name='estado de firma')),
                ('archivo_firmado', models.FileField(blank=True, upload_to='epis/firmas/', verbose_name='acuse firmado (PDF)')),
                ('fecha_firma', models.DateField(blank=True, null=True, verbose_name='fecha de firma')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas_epi', to='companies.company', verbose_name='empresa')),
                ('entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma', to='epis.entregaepi', verbose_name='entrega')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas_epi', to='workers.worker', verbose_name='trabajador')),
            ],
            options={
                'verbose_name': 'firma de entrega de EPI',
                'verbose_name_plural': 'firmas de entrega de EPI',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['empresa', 'estado_firma'], name='epis_firmae_empresa_89745a_idx'), models.Index(fields=['empresa', 'trabajador'], name='epis_firmae_empresa_08c800_idx')],
            },
        ),
    ]
