# Generated by Django 6.0.5 on 2026-07-13 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_migrate_platform_admin_role'),
        ('epis', '0002_procedimientoentrega_firmaentrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('categoria', models.CharField(choices=[('cabeza', 'Proteccion de la cabeza'), ('manos', 'Proteccion de las manos'), ('pies', 'Proteccion de los pies'), ('ojos', 'Proteccion ocular'), ('oidos', 'Proteccion auditiva'), ('respiratoria', 'Proteccion respiratoria'), ('corporal', 'Proteccion corporal'), ('otro', 'Otro')], default='cabeza', max_length=20, verbose_name='categoria')),
                ('riesgos_proteccion', models.TextField(help_text='Describe los riesgos frente a los que protege este EPI.', verbose_name='riesgos que protege')),
                ('norma_eu', models.CharField(help_text='Norma europea que debe cumplir (ej: EN 166, EN 388, EN ISO 20345).', max_length=100, verbose_name='norma UNE / EN')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripcion')),
                ('imagen', models.FileField(blank=True, upload_to='epis/catalogo/', verbose_name='imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'catalogo de EPI',
                'verbose_name_plural': 'catalogo de EPIs',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='tipoepi',
            name='empresa',
        ),
        migrations.RemoveIndex(
            model_name='epi',
            name='epis_epi_empresa_e16b55_idx',
        ),
        migrations.AddField(
            model_name='epi',
            name='catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epis', to='epis.catalogoepi', verbose_name='catalogo de EPI'),
        ),
        migrations.AddIndex(
            model_name='epi',
            index=models.Index(fields=['empresa', 'catalogo'], name='epis_epi_empresa_dd56b8_idx'),
        ),
        migrations.RemoveField(
            model_name='epi',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='TipoEPI',
        ),
    ]
