# Generated by Django 6.0.4 on 2026-07-15 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('categoria', models.CharField(choices=[('maquinaria', 'Maquinaria'), ('herramientas', 'Herramientas'), ('vehiculos', 'Vehiculos'), ('andamios', 'Andamios'), ('gruas', 'Gruas'), ('escaleras', 'Escaleras'), ('elevacion', 'Equipos de elevacion'), ('instalaciones', 'Instalaciones fijas'), ('otro', 'Otro')], default='maquinaria', max_length=20, verbose_name='categoria')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripcion')),
                ('imagen', models.FileField(blank=True, upload_to='equipos/tipos/', verbose_name='imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_equipo', to='companies.company', verbose_name='empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'tipo de equipo',
                'verbose_name_plural': 'tipos de equipo',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EquipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre / identificacion')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='numero de serie')),
                ('numero_bien', models.CharField(blank=True, max_length=100, verbose_name='numero de bien')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='fecha de compra')),
                ('fecha_puesta_marcha', models.DateField(blank=True, null=True, verbose_name='fecha de puesta en marcha')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='ubicacion / centro de trabajo')),
                ('vida_util_meses', models.PositiveIntegerField(blank=True, null=True, verbose_name='vida util (meses)')),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('en_mantenimiento', 'En mantenimiento'), ('retirado', 'Retirado'), ('baja', 'Baja')], default='operativo', max_length=20, verbose_name='estado')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('manual_instrucciones', models.FileField(blank=True, upload_to='equipos/manuales/', verbose_name='manual de instrucciones (PDF)')),
                ('declaracion_ce', models.FileField(blank=True, upload_to='equipos/declaraciones_ce/', verbose_name='declaracion CE de conformidad (PDF)')),
                ('certificado_instalacion', models.FileField(blank=True, upload_to='equipos/certificados_instalacion/', verbose_name='certificado de instalacion (PDF)')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_trabajo', to='companies.company', verbose_name='empresa')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_trabajo_responsable', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='work_equipment.tipoequipo', verbose_name='tipo de equipo')),
            ],
            options={
                'verbose_name': 'equipo de trabajo',
                'verbose_name_plural': 'equipos de trabajo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('fecha', models.DateField(verbose_name='fecha de mantenimiento')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('predictivo', 'Predictivo')], default='preventivo', max_length=20, verbose_name='tipo de mantenimiento')),
                ('descripcion', models.TextField(verbose_name='descripcion del trabajo realizado')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo estimado')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='proveedor externo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_equipo', to='companies.company', verbose_name='empresa')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='work_equipment.equipotrabajo', verbose_name='equipo')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_equipo_realizados', to=settings.AUTH_USER_MODEL, verbose_name='realizado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'mantenimiento de equipo',
                'verbose_name_plural': 'mantenimientos de equipo',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['empresa', 'tipo'], name='work_equipm_empresa_51f5bd_idx'), models.Index(fields=['fecha'], name='work_equipm_fecha_ed0a3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='RevisionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('fecha', models.DateField(verbose_name='fecha de revision')),
                ('resultado', models.CharField(choices=[('conforme', 'Conforme'), ('observaciones', 'Con observaciones'), ('no_conforme', 'No conforme'), ('reparado', 'Reparado necesario')], default='conforme', max_length=20, verbose_name='resultado')),
                ('proxima_revision', models.DateField(blank=True, null=True, verbose_name='proxima revision')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_equipo', to='companies.company', verbose_name='empresa')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='work_equipment.equipotrabajo', verbose_name='equipo')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_equipo_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='realizado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'revision de equipo',
                'verbose_name_plural': 'revisiones de equipo',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['empresa', 'resultado'], name='work_equipm_empresa_7a54af_idx'), models.Index(fields=['fecha'], name='work_equipm_fecha_064bde_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='equipotrabajo',
            index=models.Index(fields=['empresa', 'estado'], name='work_equipm_empresa_9831f0_idx'),
        ),
        migrations.AddIndex(
            model_name='equipotrabajo',
            index=models.Index(fields=['empresa', 'tipo'], name='work_equipm_empresa_8dd70c_idx'),
        ),
    ]
