# Generated by Django 6.0.4 on 2026-07-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipotrabajo',
            name='certificado_instalacion',
            field=models.FileField(blank=True, upload_to='equipos/certificados_instalacion/', verbose_name='certificado de instalacion (PDF)'),
        ),
        migrations.AddField(
            model_name='equipotrabajo',
            name='declaracion_ce',
            field=models.FileField(blank=True, upload_to='equipos/declaraciones_ce/', verbose_name='declaracion CE de conformidad (PDF)'),
        ),
        migrations.AddField(
            model_name='equipotrabajo',
            name='manual_instrucciones',
            field=models.FileField(blank=True, upload_to='equipos/manuales/', verbose_name='manual de instrucciones (PDF)'),
        ),
    ]
