# Generated by Django 6.0.5 on 2026-05-09 05:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('workcenters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre del puesto')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='departamento')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'puesto de trabajo',
                'verbose_name_plural': 'puestos de trabajo',
                'ordering': ['company__legal_name', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='apellidos')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='DNI/NIE')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Introduce un teléfono válido.', regex='^[0-9+\\s()-]{7,20}$')], verbose_name='teléfono')),
                ('employee_code', models.CharField(blank=True, max_length=50, verbose_name='código de empleado')),
                ('social_security_number', models.CharField(blank=True, max_length=30, verbose_name='nº seguridad social')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='fecha de alta')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('employment_status', models.CharField(choices=[('active', 'Activo'), ('leave', 'Baja'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='estado laboral')),
                ('especially_sensitive', models.BooleanField(default=False, verbose_name='especial sensibilidad')),
                ('temporary_worker', models.BooleanField(default=False, verbose_name='trabajador temporal')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='companies.company', verbose_name='empresa')),
                ('job_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='workers.jobposition', verbose_name='puesto de trabajo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario del sistema')),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='workcenters.workcenter', verbose_name='centro de trabajo')),
            ],
            options={
                'verbose_name': 'trabajador',
                'verbose_name_plural': 'trabajadores',
                'ordering': ['company__legal_name', 'last_name', 'first_name'],
                'unique_together': {('company', 'employee_code')},
            },
        ),
    ]
