# Generated by Django 6.0.5 on 2026-05-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='código de empleado'),
        ),
    ]
