# Generated by Django 6.0.5 on 2026-05-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_worker_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI / NIE'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nº Seguridad Social'),
        ),
    ]
