# Generated by Django 6.0.5 on 2026-07-13 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_migrate_platform_admin_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('plan', 'Plan de Emergencia'), ('extintor', 'Extintor'), ('evacuacion', 'Ruta de Evacuación'), ('simulacro', 'Simulacro'), ('protocolo', 'Protocolo de Actuación')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('ubicacion', models.CharField(blank=True, default='', max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('proximo_simulacro', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='medidas_emergencia/')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas_emergencia', to='companies.company')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidas_emergencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medida de Emergencia',
                'verbose_name_plural': 'Medidas de Emergencia',
                'ordering': ['tipo', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='HistorialSimulacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('participantes', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='emergency_measures.medidaemergencia')),
            ],
            options={
                'verbose_name': 'Historial de Simulacro',
                'verbose_name_plural': 'Historial de Simulacros',
                'ordering': ['-fecha'],
            },
        ),
    ]
