# Generated by Django 6.0.5 on 2026-07-13 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_migrate_platform_admin_role'),
        ('workers', '0004_alter_worker_national_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioProteccionIncendios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('icono', models.CharField(blank=True, default='', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medio de Protección contra Incendios',
                'verbose_name_plural': 'Medios de Protección contra Incendios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EntregaInformacionEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('tipo_informacion', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('firma_trabajador', models.BooleanField(default=False)),
                ('archivo', models.FileField(blank=True, upload_to='medidas_emergencia/entregas_info/')),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_info_emergencia', to='companies.company')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_info_emergencia', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Entrega de Información de Emergencia',
                'verbose_name_plural': 'Entregas de Información de Emergencia',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='EquipoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('jefe', 'Jefe de Emergencia'), ('sustituto', 'Sustituto del Jefe'), ('intervencion', 'Equipo de Intervención'), ('primeros_auxilios', 'Equipo de Primeros Auxilios'), ('evacuacion', 'Equipo de Evacuación'), ('comunicaciones', 'Equipo de Comunicaciones')], max_length=20)),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('designacion_file', models.FileField(blank=True, upload_to='medidas_emergencia/designaciones/')),
                ('formacion_file', models.FileField(blank=True, upload_to='medidas_emergencia/formacion_equipos/')),
                ('descripcion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_emergencia', to='companies.company')),
            ],
            options={
                'verbose_name': 'Equipo de Emergencia',
                'verbose_name_plural': 'Equipos de Emergencia',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanAutoproteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_plan', models.FileField(blank=True, upload_to='medidas_emergencia/plan/')),
                ('file_plano', models.FileField(blank=True, upload_to='medidas_emergencia/plano/')),
                ('notas_plano', models.TextField(blank=True, default='')),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('proxima_revision', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_autoproteccion', to='companies.company')),
            ],
            options={
                'verbose_name': 'Plan de Autoprotección',
                'verbose_name_plural': 'Planes de Autoprotección',
            },
        ),
        migrations.CreateModel(
            name='RegistroSimulacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, default='')),
                ('participantes', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('duracion_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, upload_to='medidas_emergencia/simulacros/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacros', to='companies.company')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Simulacro',
                'verbose_name_plural': 'Registros de Simulacros',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaMedioProteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=300)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_proteccion', to='companies.company')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='emergency_measures.medioproteccionincendios')),
            ],
            options={
                'verbose_name': 'Medio de Protección de la Empresa',
                'verbose_name_plural': 'Medios de Protección de la Empresa',
                'unique_together': {('company', 'medio')},
            },
        ),
        migrations.CreateModel(
            name='MiembroEquipoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, default='', max_length=100)),
                ('designacion_file', models.FileField(blank=True, upload_to='medidas_emergencia/miembros_designaciones/')),
                ('formacion_file', models.FileField(blank=True, upload_to='medidas_emergencia/miembros_formacion/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='emergency_measures.equipoemergencia')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_emergencia', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Miembro del Equipo de Emergencia',
                'verbose_name_plural': 'Miembros de Equipos de Emergencia',
                'unique_together': {('equipo', 'trabajador')},
            },
        ),
    ]
