# Generated by Django 6.0.4 on 2026-07-15 17:46

import apps.prevention_plan.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPrevention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('politica', models.FileField(blank=True, null=True, upload_to=apps.prevention_plan.models.upload_politica_path, verbose_name='Politica de prevencion (PDF)')),
                ('politica_fecha_subida', models.DateField(blank=True, null=True, verbose_name='Fecha de subida de politica')),
                ('politica_firmada', models.BooleanField(default=False, verbose_name='Politica firmada')),
                ('organigrama', models.FileField(blank=True, null=True, upload_to=apps.prevention_plan.models.upload_organigrama_path, verbose_name='Organigrama (PDF/Imagen)')),
                ('organigrama_texto', models.TextField(default='Estructura organizativa:\n\n1. Empresario / Direction General\n   - Responsable maximo de la empresa\n   - Aprueba el Plan de Prevencion\n\n2. Encargado / Mando intermedio\n   - Supervisa la actividad preventiva en su area\n   - Aplica las medidas preventivas\n\n3. Trabajadores/as\n   - Cumplen las normas de seguridad e higiene\n   - Colaboran en la prevencion de riesgos', verbose_name='Texto del organigrama')),
                ('delegado_prl', models.CharField(choices=[('si', 'Si'), ('no', 'No'), ('no_aplica', 'No aplica')], default='no_aplica', max_length=20, verbose_name='Delegado de PRL')),
                ('delegado_fecha_designacion', models.DateField(blank=True, null=True, verbose_name='Fecha designacion delegado')),
                ('delegado_formacion', models.BooleanField(default=False, verbose_name='Delegado con formacion')),
                ('doc_designacion_delegado', models.FileField(blank=True, null=True, upload_to=apps.prevention_plan.models.upload_doc_delegado_path, verbose_name='Doc. designacion delegado')),
                ('doc_formacion_delegado', models.FileField(blank=True, null=True, upload_to=apps.prevention_plan.models.upload_doc_delegado_path, verbose_name='Doc. formacion delegado')),
                ('recurso_preventivo', models.CharField(choices=[('si', 'Si'), ('no', 'No'), ('no_aplica', 'No aplica')], default='no_aplica', max_length=20, verbose_name='Recurso preventivo')),
                ('recurso_actividades', models.TextField(blank=True, default='', verbose_name='Actividades en las que se requiere recurso preventivo')),
                ('recurso_fecha_designacion', models.DateField(blank=True, null=True, verbose_name='Fecha designacion recurso preventivo')),
                ('recurso_formacion', models.BooleanField(default=False, verbose_name='Recurso preventivo con formacion')),
                ('doc_designacion_recurso', models.FileField(blank=True, null=True, upload_to=apps.prevention_plan.models.upload_doc_recurso_path, verbose_name='Doc. designacion recurso preventivo')),
                ('doc_formacion_recurso', models.FileField(blank=True, null=True, upload_to=apps.prevention_plan.models.upload_doc_recurso_path, verbose_name='Doc. formacion recurso preventivo')),
                ('funciones_responsabilidades', models.TextField(default='Funciones y responsabilidades segun el organigrama:\n\nEMPRESARIO/DIRECCION:\n- Aprobar y revisar el Plan de Prevencion\n- Dotar los medios necesarios para la prevencion\n- Garantizar la formacion de los trabajadores\n- Designar al delegado de prevencion y recurso preventivo\n\nENCARGADO/MANDO INTERMEDIO:\n- Supervisar el cumplimiento de las medidas preventivas\n- Informar de los riesgos a los trabajadores\n- Colaborar en la evaluacion de riesgos\n- Formar a los trabajadores nuevos\n\nTRABAJADORES/AS:\n- Cumplir las normas de seguridad e higiene\n- Usar correctamente los EPIs\n- Informar de las situaciones de riesgo\n- Colaborar en la prevencion de riesgos', verbose_name='Funciones y responsabilidades')),
                ('utiliza_ett', models.BooleanField(default=False, verbose_name='Utiliza empresas de ETT')),
                ('puestos_ett', models.TextField(blank=True, default='', verbose_name='Puestos cubiertos por ETT')),
                ('tiene_teletrabajo', models.BooleanField(default=False, verbose_name='Tiene trabajadores en teletrabajo')),
                ('puestos_teletrabajo', models.TextField(blank=True, default='', verbose_name='Puestos en teletrabajo')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prevention_plan', to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Plan de Prevencion',
                'verbose_name_plural': 'Planes de Prevencion',
                'ordering': ['company'],
            },
        ),
    ]
