# Generated by Django 6.0.5 on 2026-05-09 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre del centro')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='código interno')),
                ('address', models.CharField(max_length=255, verbose_name='dirección')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='código postal')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='provincia')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='persona de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono de contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='correo de contacto')),
                ('activity', models.CharField(blank=True, max_length=255, verbose_name='actividad del centro')),
                ('worker_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='número de trabajadores')),
                ('risk_level', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('very_high', 'Muy alto')], default='low', max_length=20, verbose_name='nivel de riesgo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_centers', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'centro de trabajo',
                'verbose_name_plural': 'centros de trabajo',
                'ordering': ['company__legal_name', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
