# Generated by Django 6.0.5 on 2026-07-13 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_migrate_platform_admin_role'),
        ('corrective_actions', '0001_initial'),
        ('workcenters', '0001_initial'),
        ('workers', '0004_alter_worker_national_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CausaAccidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('categoria', models.CharField(choices=[('inmediata', 'Causa inmediata'), ('basica', 'Causa basica'), ('organizativa', 'Causa organizativa')], default='inmediata', max_length=20, verbose_name='categoria')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='causas_accidente', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'causa de accidente',
                'verbose_name_plural': 'causas de accidente',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='codigo')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('fecha', models.DateTimeField(verbose_name='fecha y hora del accidente')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='ubicacion especifica')),
                ('tipo', models.CharField(choices=[('trabajo', 'Accidente de trabajo'), ('itinere', 'Accidente in itinere')], default='trabajo', max_length=20, verbose_name='tipo de accidente')),
                ('gravedad', models.CharField(choices=[('sin_baja', 'Sin baja'), ('baja_temporal', 'Baja temporal'), ('baja_permanente', 'Baja permanente'), ('mortal', 'Mortal')], default='sin_baja', max_length=20, verbose_name='gravedad')),
                ('tipo_lesion', models.CharField(choices=[('cortes', 'Cortes'), ('fracturas', 'Fracturas'), ('contusiones', 'Contusiones'), ('quemaduras', 'Quemaduras'), ('intoxicacion', 'Intoxicacion'), ('atrapamiento', 'Atrapamiento'), ('caida', 'Caida'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='tipo de lesion')),
                ('parte_cuerpo', models.CharField(blank=True, max_length=200, verbose_name='parte del cuerpo afectada')),
                ('descripcion', models.TextField(verbose_name='descripcion del accidente')),
                ('testigos', models.TextField(blank=True, verbose_name='testigos')),
                ('notify_salud', models.BooleanField(default=False, verbose_name='notificado a vigilancia de la salud')),
                ('notify_inspeccion', models.BooleanField(default=False, verbose_name='notificado a inspeccion de trabajo')),
                ('fecha_notificacion', models.DateField(blank=True, null=True, verbose_name='fecha de notificacion')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_investigacion', 'En investigacion'), ('cerrado', 'Cerrado')], default='abierto', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidentes', to='workcenters.workcenter', verbose_name='centro de trabajo')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidentes_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidentes', to='companies.company', verbose_name='empresa')),
                ('nc_generada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidentes', to='corrective_actions.noconformidad', verbose_name='NC generada')),
                ('trabajador_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidentes', to='workers.worker', verbose_name='trabajador afectado')),
                ('causas', models.ManyToManyField(blank=True, related_name='accidentes', to='incidents.causaaccidente', verbose_name='causas identificadas')),
            ],
            options={
                'verbose_name': 'accidente',
                'verbose_name_plural': 'accidentes',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='codigo')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('fecha', models.DateTimeField(verbose_name='fecha y hora del incidente')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='ubicacion especifica')),
                ('descripcion', models.TextField(verbose_name='que ocurrio')),
                ('potencial_dano', models.TextField(blank=True, verbose_name='que dano podria haber causado')),
                ('testigos', models.TextField(blank=True, verbose_name='testigos')),
                ('gravedad_potencial', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave'), ('muy_grave', 'Muy grave')], default='leve', max_length=20, verbose_name='gravedad potencial')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_estudio', 'En estudio'), ('cerrado', 'Cerrado')], default='abierto', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='workcenters.workcenter', verbose_name='centro de trabajo')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='companies.company', verbose_name='empresa')),
                ('trabajador_reports', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_reportados', to='workers.worker', verbose_name='trabajador que reporto')),
            ],
            options={
                'verbose_name': 'incidente',
                'verbose_name_plural': 'incidentes',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigacionAccidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('metodologia', models.CharField(choices=[('_5_porques', '5 Porques'), ('ishikawa', 'Ishikawa (Espina de pez)'), ('arbol_causas', 'Arbol de causas'), ('otro', 'Otro')], default='_5_porques', max_length=20, verbose_name='metodologia de analisis')),
                ('descripcion_ideal', models.TextField(blank=True, verbose_name='descripcion de lo que deberia haber pasado')),
                ('descripcion_real', models.TextField(blank=True, verbose_name='descripcion de lo que realmente paso')),
                ('causas_inmediatas', models.TextField(blank=True, verbose_name='causas inmediatas')),
                ('causas_basicas', models.TextField(blank=True, verbose_name='causas basicas')),
                ('causas_organizativas', models.TextField(blank=True, verbose_name='causas organizativas')),
                ('conclusiones', models.TextField(blank=True, verbose_name='conclusiones')),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('completada', 'Completada')], default='en_curso', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accidente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigacion', to='incidents.accidente', verbose_name='accidente')),
                ('investigador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigaciones_accidente', to=settings.AUTH_USER_MODEL, verbose_name='investigador')),
            ],
            options={
                'verbose_name': 'investigacion de accidente',
                'verbose_name_plural': 'investigaciones de accidente',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='accidente',
            index=models.Index(fields=['empresa', 'estado'], name='incidents_a_empresa_73d31f_idx'),
        ),
        migrations.AddIndex(
            model_name='accidente',
            index=models.Index(fields=['empresa', 'centro_trabajo'], name='incidents_a_empresa_cad03f_idx'),
        ),
        migrations.AddIndex(
            model_name='accidente',
            index=models.Index(fields=['fecha'], name='incidents_a_fecha_24a1af_idx'),
        ),
        migrations.AddIndex(
            model_name='incidente',
            index=models.Index(fields=['empresa', 'estado'], name='incidents_i_empresa_ff6711_idx'),
        ),
        migrations.AddIndex(
            model_name='incidente',
            index=models.Index(fields=['empresa', 'centro_trabajo'], name='incidents_i_empresa_a6ff9d_idx'),
        ),
        migrations.AddIndex(
            model_name='incidente',
            index=models.Index(fields=['fecha'], name='incidents_i_fecha_3b0c65_idx'),
        ),
    ]
