# Generated by Django 6.0.5 on 2026-07-13 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_migrate_platform_admin_role'),
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacionaccidente',
            name='acto_condicion_detectada',
            field=models.TextField(blank=True, verbose_name='acto o condicion detectada'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='coste',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='coste estimado'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='edad del trabajador'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='fecha_firma',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de firma'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='hora_dia',
            field=models.TimeField(blank=True, null=True, verbose_name='hora del dia'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='horas_trabajador',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='horas trabajadas (1-8)'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='medidas_preventivas',
            field=models.TextField(blank=True, verbose_name='medidas preventivas propuestas'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='plazo',
            field=models.DateField(blank=True, null=True, verbose_name='plazo de implantacion'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='puesto_trabajo',
            field=models.CharField(blank=True, max_length=200, verbose_name='puesto de trabajo'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigaciones_responsable', to=settings.AUTH_USER_MODEL, verbose_name='responsable de medidas'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigaciones_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='revisor'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='riesgo_en_er',
            field=models.BooleanField(default=False, verbose_name='riesgo en evaluacion de riesgos'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='riesgo_identificado',
            field=models.CharField(blank=True, choices=[('', '--- Seleccionar ---'), ('caidas_mismo_nivel', 'Caídas al mismo nivel'), ('caidas_distinto_nivel', 'Caídas a distinto nivel'), ('caida_objetos', 'Caída de objetos'), ('proyeccion_fragmentos', 'Proyección de fragmentos y/o partículas'), ('atrapamientos', 'Atrapamientos'), ('golpes', 'Golpes contra objetos'), ('cortes', 'Cortes y cortaduras'), ('quemaduras', 'Quemaduras'), ('electrocucion', 'Electrocución'), ('explosion', 'Explosión'), ('incendio', 'Incendio'), ('intoxicacion', 'Intoxicación'), ('asfixia', 'Asfixia'), ('ahogamiento', 'Ahogamiento'), ('sordera', 'Pérdida auditiva'), ('lesiones_osteomusculares', 'Lesiones osteomusculares'), ('enfermedad_profesional', 'Enfermedad profesional'), ('ergonomico', 'Riesgo ergonómico'), ('psicosocial', 'Riesgo psicosocial'), ('biologico', 'Riesgo biológico'), ('radiacion', 'Exposición a radiaciones'), ('derrame_sustancias', 'Derrame de sustancias'), ('otro', 'Otro')], max_length=40, verbose_name='riesgo identificado'),
        ),
        migrations.AddField(
            model_name='investigacionaccidente',
            name='tiempo_puesto',
            field=models.CharField(blank=True, max_length=100, verbose_name='tiempo en el puesto de trabajo'),
        ),
        migrations.CreateModel(
            name='ProcedimientoInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripcion')),
                ('archivo', models.FileField(upload_to='incidentes/procedimientos/', verbose_name='archivo del procedimiento')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='version')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_investigacion', to='companies.company', verbose_name='empresa')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimientos_investigacion', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
            ],
            options={
                'verbose_name': 'procedimiento de investigacion',
                'verbose_name_plural': 'procedimientos de investigacion',
                'ordering': ['-created_at'],
            },
        ),
    ]
